### ISSUE TITLE
Enhancement: allow the use of floats in timing modifiers

### ISSUE THREAD

**Issue by GoldenJoe** [HeroTransitions/Hero#218]
OK:
`myView.heroModifiers = [.fade, .scale(0.5)] `

OK:
`myView.heroModifiers = [.duration(1), .fade, .scale(0.5)] `

ERROR: Static member 'fade' cannot be used on instance of type 'HeroModifier'
`myView.heroModifiers = [.duration(0.35), .fade, .scale(0.5)] `

OK:
`let t : TimeInterval = 0.35`
`myView.heroModifiers = [.duration(t), .fade, .scale(0.5)]`

**Comment by lkzhao** [comment]
@GoldenJoe Maybe try
```swift
myView.heroModifiers = [HeroModifier.duration(0.35), .fade, .scale(0.5)]
```

Swift is getting confused about the type. Not sure why... Let me know you if find an alternate way to solve this.

**Comment by stevejcox** [comment]
To add to this, in some instances (like opacity), you may need to add the type to the arguments. EG: .opacity(CGFloat(0.35)) as Swift is unable to determine which opacity func to use.
