### ISSUE TITLE
Is there a way to transition a view that uses a CAShapeLayer for a mask to one that uses a different mask?

### ISSUE THREAD

**Issue by GoldenJoe** [HeroTransitions/Hero#219]
Can Hero be used to transition between UIViews that use a CAShapeLayer as a mask? Maybe instead the path for the CAShapeLayer can be modified?

I have a custom header view that I made, which includes a masked background image, a title, and optionally some extra labels/images. If I wanted to change constraints, or the dimensions of the view, is there a way to have Hero account for them in its interactive transitions?

[Here is a visualization of what I'm talking about](http://imgur.com/a/hcu7E)

**Comment by lkzhao** [comment]
Something I want to do too. Will work on this after 1.0.0 is stable.

**Comment by k-nar** [comment]
I there a way with the current version to do a custom animation on unmatched views
I'd like to let hero do the matched views transitions while I do a custom mask animation on the unmatched background view

**Comment by anitaa1990** [comment]
Hey is bubble transition support added to the lib?
