### ISSUE TITLE
In-call/hotspot status bar breaks transition

### ISSUE THREAD

**Issue by LcTwisk** [HeroTransitions/Hero#222]
Transitioning between VC's during a call or when the phone is used as hotspot messes up their positions (frames get shifted upwards by 20 every transition)

This problem can be reproduced by enabling the status bar in the 'HeroExamples' applications, and perform some transitions. 
Kind of a corner case scenario, but would still be nice if you can take a look at it!

![img_1265](https://user-images.githubusercontent.com/3274157/27039639-c17f61dc-4f8e-11e7-9a2d-b3054c048595.PNG)

**Comment by LcTwisk** [comment]
Just found out that setting:

```
modalPresentationStyle = .custom
modalPresentationCapturesStatusBarAppearance = true
```
in the presented VC kind of fixes the problem. The frame jumps back to the correct position after the transition is finished, which still looks a bit weird because the frame is just set without animation

**Comment by lkzhao** [comment]
Hmm, will double check this. thanks for reporting.

**Comment by baims** [comment]
@LcTwisk @lkzhao is there a workaround for that in navigationControllers ?

**Comment by aborren** [comment]
I also found that the posted fix doesn't work for navigation controllers. @lkzhao have you got any suspicion on what might be causing this? I have some time this weekend so might dig a bit into it, but I haven't had a major look at the project so would be nice with some pointers.

**Comment by ed-mejia** [comment]
Any possible workaround for this? I've tried @LcTwisk solution but it doesn't work either that way for me :(, The frame does not jumps back to the correct position after the transition is finished 👎

**Comment by beimen** [comment]
@baims @ed-mejia 

I wrote a extension of UIApplication:
```
extension UIApplication {
    func resetKeyViewPosition() {
        if statusBarFrame.height == 40 {
            if let vc = keyWindow?.rootViewController {
                let frame = vc.view.frame
                vc.view.frame = CGRect(x: frame.minX, y: frame.minY, width: frame.width, height: frame.height + 20)
            }
        }
    }
}
```

Call `UIApplication.shared.resetKeyViewPosition()` after the transition was ended.

It did work for me. But I hope I can avoid these codes.

And thanks for @lkzhao 's working. Hero is a very powerful tool.

**Comment by raulferrer** [comment]
Had the answer solved your issue?
