### ISSUE TITLE
[Bug] iOS 11, Navigation Large text animation issue with hero

### ISSUE THREAD

**Issue by AfrozZaheer** [HeroTransitions/Hero#290]
Hi, I'm using navigation large text and while transition to next VC navigation glitch and jerking. 
Can you look at this?

**Comment by AfrozZaheer** [comment]
When navigation bar transulant = false Hero animation issues with large title.

**Comment by remithaunay** [comment]
@lkzhao is there any fix to prevent us from using a non-translucent navigation bar and having any related issues ?

**Comment by MyGuySi** [comment]
Can this be reopened? Seems like it's still a problem. I haven't set a translucent navigation bar and it's still glitching right at the start of the transition

**Comment by goghvanmr** [comment]
I have the same problem here, could you please reopen this issue?

**Comment by guseducampos** [comment]
Hi, I have a similar problem and I think it could be related, I'm doing a transition from a UIViewController with a navigation bar hidden to other that also has navigation bar hidden, this works like a charm, but when I moved from the first ViewController (from the initial view controller that has hide the navigation bar) to other that needs to show the navigation bar (this doesn't perform any custom transition just a simple push) for some reason the large text title disappear, but when I disabled hero before move to this view controller the large titles appear again.

**Comment by Sarquella** [comment]
I had similar issues when using large titles with non-translucent navigation bar. I was able to fix it just by adding the following line:

`Hero.shared.containerColor = .clear`

**Comment by piemonte** [comment]
i'm seeing this issue as well, would also like to request a reopen
