### ISSUE TITLE
No transition from button in UINavigationBar

### ISSUE THREAD

**Issue by LivioGama** [HeroTransitions/Hero#314]
Hello,

I have a UIButton in UIButtonBarItem in my UINavigationBar where I setted heroID, but the transition is not made. If I set the heroID to a view in my viewcontroller's view, it works properly.

It looks like Hero check every subviews in the viewcontroller's view, but not in the UINavigationController view (including the UINavigationBar).

Any idea how I can achieve that ?

**Comment by lkzhao** [comment]
If you are showing a view controller inside the navigation controller, then Hero has no controller over the navigation bar. But you can use modal transition to allow hero handle navigation bar animation for you.

**Comment by LivioGama** [comment]
![screenrecording_11-05-2017 12 54](https://user-images.githubusercontent.com/6930498/32414503-c2cdd4f8-c228-11e7-9afb-a793fa61a274.gif)

You see, it works with the view inside the view controller but not with the view inside the UINavigationBar

**Comment by patthehuman** [comment]
We am having the same issue as the person above. Is there a solution for this?
