### ISSUE TITLE
Tab bar not visible when dismiss view controller

### ISSUE THREAD

**Issue by phiren** [HeroTransitions/Hero#320]
I have used library for dismiss view controller with pan gesture.

Application have tab bar with 4 tabs. on first tab bar, there is tableview and on selection of row presenting view controller which should be dismissed with swipe right to left.

It works fine without any issue, only problem is the background view controller, it does not show tab bar. Also the background view is blurred, it seems taking snapshot of screen and showing that snapshot and it does not include tab bar in snapshot.

Let me know if required more information.

**Comment by lkzhao** [comment]
Is your first tap containing a navigation controller? Did you use the navigation controller to present your view controller?
