### ISSUE TITLE
Question: changing the final state (or snapshot?) of a view during interactive transition

### ISSUE THREAD

**Issue by curato-research** [HeroTransitions/Hero#322]
I'm using a pinch gesture to interactively transition from a UIImageView to a ZoomViewController that has the same UIImageView inside zooming UIScrollView. I update the progress with some modification of the gesture.scale and I have predefined zoom scale for the ZoomViewController. This works great. 

Now I want to use the scale at the end of the gesture to be used in the ZoomViewController, i.e. I want the target state to depend on the gesture scale. If I set the scale to the new ZoomViewController the end state after the transition is as expected, but as the transition completes it first animates to it's initially set zoom scale before snapping to the final state.

I expect that I need to modify the final state of the UIImageView, but I can't figure out how to exactly do this. Note that I don't want to apply new modifiers to the animation, just the end state of the animation. I've looked at HeroPlugin but I don't grasp how I should implement this.

**Comment by fulcov** [comment]
I've spent some more time looking into HeroPlugin, but I can only manage to modify the state during transition.

Perhaps I should set a new snapshot for the view, or create a new animator altogether? But it looks like there is no API for this, all those properties are internal.

**Comment by lkzhao** [comment]
This is not something that Hero currently support. I wish to do this too. If you are interested in implement this feature, let me know and I can give you some guidance.

**Comment by fulcov** [comment]
Thanks for the response. I'm occupied until the end of the year, but I might help implement this around January. I will be in touch.

**Comment by lkzhao** [comment]
Cool, no worry. I might find some time to implement this.

**Comment by mclovink** [comment]
Hello lkzhao, 
I'm working with fulco v on this project and we are planning on implementing this feature. Guidance will definitely be helpful so we're looking forward to hearing from you about this. 
Kind regards, Menno

**Comment by fulcov** [comment]
Hi Luke, 

As Menno mentioned above we're looking to implement this above mentioned feature into Hero. Menno will be having a look by himself with some of my findings from working with Hero a few months ago. However, any directions from you will definitely be helpful, so if you can find some time, please do :)

Best regards,
Fulco

**Comment by ManueGE** [comment]
Hi @fulcov, @mennolovink 

you mentioned

> I've spent some more time looking into HeroPlugin, but I can only manage to modify the state during the transition.

How did you do it? I need to change the state during a transition too, but I don't have a clue. 

Thanks :)
