### ISSUE TITLE
NavigationBarButton not triggering animation

### ISSUE THREAD

**Issue by ssaylanc** [HeroTransitions/Hero#324]
My setup is NavigationController -> TableView -> CollectionView. And I am using ListToGrid example as reference. 
- HeroViewControllerDelegate is not called unless I set navigationController?.isHeroEnabled = true in viewDidLoad of TableView.
- HeroViewControllerDelegate is called but there is no animation.

I tried to add a segue from the storyboard from barButtonItem to collectionView. There is no transition animation to collectionView, but this time because of the segue there is a back button on CollectionView Navbar. When I hit the backButton, transition to the tableView is animated.

I can't get all the animations work as intended.

**Comment by lkzhao** [comment]
What kind of segue did you use.

**Comment by EgorkZe** [comment]
@ssaylanc Did you find a solution?

**Comment by MaximGolovlev** [comment]
> @ssaylanc Did you find a solution?

after a while, I figured out that you need to apply hero.isEnabled = true to UINavigationVC in storyboards
