### ISSUE TITLE
Enabling HeroId creating few issues in UITabBarController

### ISSUE THREAD

**Issue by Ruthwick** [HeroTransitions/Hero#336]
Hi, I have a implemented a view controller flow inside a UINavigationController through a UITabBarController. I facing these following Issue
1) Hide nav bar on push  gets disabled when view is popedback
2) Adding transparent navigation bar creates black bar instead of clear colour
3) Transition are not executing properly.
But if i disable heroId id everything works fine. Any suggestion would be very helpful.

**Comment by lkzhao** [comment]
Can you provide a sample project to demonstrate the issues you are having?

**Comment by Ruthwick** [comment]
Hi, Sorry for the late reply. I have attached an example project with the following issues i am having
1) Popping back the view, tab bar gets disabled on hide nav bar on push with heroId enabled.
2) Swipe back to pop a view is not working.
Transparent navigation bar issue was because of my mistake, sorry for that and i am unable to recreate the transition issue i was facing at the moment, so i'll get back to you asap with tat. Thanks in advance.
[ExampleProject.zip](https://github.com/lkzhao/Hero/files/1508490/ExampleProject.zip)

**Comment by darshan2509** [comment]
Hi  lkzhao,
I am facing the same issue as the above example, the tab bar is disabled once the transition is over.
can you take a look into the problem/

Thanks in advance.

**Comment by adamup928** [comment]
I've also had `UITabBar` become unresponsive once the transition is over.  I've been able to mitigate it for some `UITabBar` by calling  `[tabBar.layer removeAllAnimations]` in `viewDidAppear:`.  In some cases, however, this has no effect.
