### ISSUE TITLE
setDefaultAnimationForNextTransition swift 4

### ISSUE THREAD

**Issue by vogttho** [HeroTransitions/Hero#342]
I did not find any informations about setDefaultAnimationForNextTransition to be deprecated. Hero.shared.setDefaultAnimationForNextTransition is still in the documentation.

But i get the following error:
Hero.shared.setDefaultAnimationForNextTransition not found.

**Comment by jschementi** [comment]
With v1.0.1, using the `Hero.shared.defaultAnimation` setter seems to have the same effect for me as `Hero.shared.setDefaultAnimationForNextTransition` use to.

So, instead of:
```
Hero.shared.setDefaultAnimationForNextTransition(.fade)
```

Do this:
```
Hero.shared.defaultAnimation = .fade
```

**Comment by alicksnake22** [comment]
Next Transition?

**Comment by Neilfau** [comment]
What if we want just one transition to be different to default... do we have to keep setting the the .defaultAnimation?

**Comment by halpz** [comment]
I still cannot find `setDefaultAnimationForNextTransition`

**Comment by halpz** [comment]
@JoeMatt

**Comment by halpz** [comment]
can this be reopened ? @JoeMatt
