### ISSUE TITLE
Weird rescaling during transition

### ISSUE THREAD

**Issue by timroesner** [HeroTransitions/Hero#347]
I have an issue where my label text gets duplicated and rescaled when transitioning. I was able to get a screenshot. I imagine this could be a setup issue which is why I am including code fragments below:

## Code
VC 1
```swift
isHeroEnabled = true
backgroundView.heroID = "background"
titleLbl.heroID = "title"
...
```

VC 2
```swift
isHeroEnabled = true
backgroundView.heroID = "background"
titleLbl.heroID = "title"

@objc func handlePan(gestureRecognizer:UIPanGestureRecognizer) {
        switch panGR.state {
        case .began:
            // begin the transition as normal
            dismiss(animated: true, completion: nil)
        case .changed:
            // calculate the progress based on how far the user moved
            let translation = panGR.translation(in: nil)
            let progress = translation.y / 2 / view.bounds.height
            Hero.shared.update(progress)
        default:
            // end the transition when user ended their touch
            Hero.shared.finish()
         }
}
```

## Screenshot
![img_f76093acd6ab-1](https://user-images.githubusercontent.com/13894518/33538630-559eb9aa-d877-11e7-8a25-4a1981ea7e27.jpeg)

**Comment by lkzhao** [comment]
This is because hero creates snapshots for those view that matched. It is basically taking a picture of your source view and your target view, then animate the states between.  You will need to assign heroID to the labels if you want them to be animated by hero as well..

**Comment by timroesner** [comment]
sorry for not posting the whole code, yes labels have the same heroID in both views, one is a tableView, therefore the unique ID:

```swift
departureLbl.heroID = "departure\(trip.title)"
stopsLbl.heroID = "stops\(trip.title)"
durationLbl.heroID = "duration\(trip.title)"
titleLbl.heroID = "title\(trip.title)"
```

**Comment by RyanCodes** [comment]
@timroesner ever figure this out?
