### ISSUE TITLE
Constrainted extension

### ISSUE THREAD

**Issue by dDomovoj** [HeroTransitions/Hero#348]
It would be great if Hero had its own constrained extension to replace calls 
like viewController.hero_makeSomething with viewController.hero.makeSomething so it will not mess up autocompletion and all Hero setup will be visually in one place

**Comment by lkzhao** [comment]
Yep, I agree. It is definitely more elegant. I just don't have the time to do it. 

Feel free to put up a PR.
Similar work have been done for YAAL by @budged: https://github.com/lkzhao/YetAnotherAnimationLibrary/pull/2
