### ISSUE TITLE
Snapshot Animation Lag

### ISSUE THREAD

**Issue by marcus433** [HeroTransitions/Hero#349]
Hello!

I have implemented a standard gesture recognizer to animate from a collection view to an expanded card. However, when panning to dismiss the view I have noticed the snapshot behind the expanded card lags slightly behind the position animation.

[https://youtu.be/eMiUA52khKE](https://youtu.be/eMiUA52khKE)

**Comment by PeeDubyaBee** [comment]
Hello,
I'm seeing the exact same issue with a pan gesture action as well:
The larger back view element is lagging a few frames (enough to be visible) from the front elements being dismissed.

**Comment by lkzhao** [comment]
Will dig into this more. Seems like some animations are using a different timing function. Can you tell me what heroModifiers you use?

**Comment by marcus433** [comment]
The "card" only had the heroModifier for .position to translate it vertically. The background overlay had a .fade. Other than that there were no other modifiers applied.
