### ISSUE TITLE
HeroModifiers not applied

### ISSUE THREAD

**Issue by Nerkyator** [HeroTransitions/Hero#350]
**OS:** _iOS 11_
**Device tried:** _iPhone 8 Simulator, iPhone 6 Simulator, iPhone 7 (real device)_
**Hero install:**  _pod "Hero"_
**Issue:**
Hero animations work great but seems that heroModifiers are not applied. I tried with a custom app and with HeroExamples app with same result.

Just to be clear:

-  on the HeroExample app in the MusicPlayer storyboard I set 
`scale(6.5) translate(600, 0)` on the play button in storyboard modifiers but nothing changes: button only translates to final position. No scale and no translation at given point.

- on custom app simply added 2 views in 2 viewControllers (same heroId and Hero enabled) and set a fade + scale animation and nothing changes: views translate on correct position but modifiers are not applied.

Am I missing something?...

**Comment by cristinaITdeveloper** [comment]
I have the same issue! This is my code in `viewDidLoad` method:
         
         isHeroEnabled = true
         poiDistanceLabel.isHeroEnabled = true
         poiDistanceLabel.heroID = "poiDistanceLabel"
         poiDistanceLabel.heroModifiers = [.fade]
         poiNameLabel.isHeroEnabled = true
         poiNameLabel.heroID = "poiNameLabel"
         poiNameLabel.heroModifiers = [.fade] 
         goButton.isHeroEnabled = true
         goButton.heroID = "goButton"
         goButton.heroModifiers = [.fade]

Where am I wrong?

**Comment by Nerkyator** [comment]
Any news about this issue?

**Comment by korre** [comment]
I'm also experiencing this. A really simple example with two view controllers. Animation of views by setting the heroID's is working well. But when setting a modifier on a UIView in the target view controller nothing happens. Tried both in story board and in code in target view controller viewDidLoad().

**Comment by gabrieldluca** [comment]
I've been replicating the views in both ViewControllers in order to animate them as "matched items". It's an ugly workaround, indeed.

**Comment by kuyazee** [comment]
Does this issue still occur with the latest releases?

**Comment by gabrieldluca** [comment]
@kuyazee Yes, it's still happening. I am unable to replicate the "Usage Example 1" in a brand-new project. Every view animates correctly — expect the white view, which contains Hero Modifiers.

**Comment by quangpc-vn** [comment]
@gabrieldluca I guest this issue is still happening. Do u have any solution for this. I want to apply spring modifier but not work.
