### ISSUE TITLE
Dismissing View not unwinding Zoom Animation in Swift 4

### ISSUE THREAD

**Issue by AlexBailey-01** [HeroTransitions/Hero#351]
This is probably user error but I searched through the documentation and the list of issues and didn't find a solution. 

**Issue:**
When using a navigation controller to segue between 2 views, the (self.dismiss(animated: true, completion: nil)) doesn't revert the heroNavigationAnimationType.  When dismissing the second View the same .zoom animation is used instead of .zoomOut

**On View1 I have:**

self.navigationController?.isHeroEnabled = true
self.navigationController?.heroNavigationAnimationType = .zoom
...
performSegue(withIdentifier: "view2", sender: self)

**On View2 I have:**

self.isHeroEnabled = true
hero_dismissViewController()

I have tried to set the heroIDs to be both the same and different values on both VCs with no change in behavior. What am I missing?   Thanks.

**Comment by zezek** [comment]
I can solve this by changing the self.navigationController?.heroNavigationAnimationType before each segue or dismiss call but that doesn't seem like the way it should work.

**Comment by lkzhao** [comment]
try `.autoReverse(presenting: .zoom)`
