### ISSUE TITLE
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [167.5 nan]'

### ISSUE THREAD

**Issue by smidaharoun** [HeroTransitions/Hero#352]
I get this error when the height of one of the views is `0` 
`Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [167.5 nan]'`

Error in `HeroCoreAnimationViewContext.swift` in line `158`

**Comment by lkzhao** [comment]
Are you using the latest version? this should have been fixed.
