### ISSUE TITLE
Different animation for push and pop using Navigation Controller.

### ISSUE THREAD

**Issue by cristinaITdeveloper** [HeroTransitions/Hero#353]
Hi! I am using this library with default animation. I only set the parameters `isHeroEnabled` and `heroID`.
Everything is ok, but I need to do a different animation for "pop" transition. How can I do?
Thank you for your help!

**Comment by cristinaITdeveloper** [comment]
Sorry. This is my code 

        self.navigationController?.isHeroEnabled = true
        self.navigationController?.heroNavigationAnimationType = .selectBy(presenting:.zoomOut, dismissing:.fade)

        let previewPoiViewController = PreviewPoiViewController()
        previewPoiViewController.isHeroEnabled = true
        previewPoiViewController.poi = self.pois[indexPath.row]
        self.navigationController?.pushViewController(previewPoiViewController, animated: true)

But `.selectBy(presenting:.zoomOut, dismissing:.fade)` not working.

Where am I wrong?

**Comment by cristinaITdeveloper** [comment]
And I cannot change `heroNavigationAnimationType` ... 
If I set it with any value, the animation doesn't change.

**Comment by arielpollack** [comment]
you should set your `UINavigationControllerDelegate` to something that will return a custom `HeroTransition` navigation delegate.

### 1. define your transition
```swift
fileprivate let heroTransition = HeroTransition()
```

### 2. set your navigation controller's delegate
```swift
self.navigationController?.delegate = self
self.navigationController?.heroNavigationAnimationType = .autoReverse(presenting: .slide(direction: .left))
```

### 3. implement delegate mothods
```swift
extension MyViewController: UINavigationControllerDelegate {
    func navigationController(_ navigationController: UINavigationController, interactionControllerFor animationController: UIViewControllerAnimatedTransitioning)
        -> UIViewControllerInteractiveTransitioning? {
        return heroTransition.navigationController(navigationController, interactionControllerFor: animationController)
    }

    func navigationController(_ navigationController: UINavigationController,
                              animationControllerFor operation: UINavigationControllerOperation,
                              from fromVC: UIViewController,
                              to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return heroTransition.navigationController(navigationController, animationControllerFor: operation, from: fromVC, to: toVC)
    }
}
```

**Comment by mickspecial** [comment]
They must have updated this because 

navigationController.hero.navigationAnimationType = .selectBy(presenting: .zoomSlide(direction: .right), dismissing:.zoomSlide(direction: .left))

Works as expected
