### ISSUE TITLE
Tab Bar Not Responding

### ISSUE THREAD

**Issue by zykyan** [HeroTransitions/Hero#354]
When i enable hero on navigation controller, with tab controller and when i hide bottom bar on push then later coming back to the view controller tab bar is not responding.
1. UIViewController(A) -> pushed to another view controller with hideBottomBarWhenPushed to true -> UIViewController(B) -> Pop View Controller -> UIViewController (A) tab bar stops responding. Tab bar will only responds after i perform some segue to other view controller and dismissing it

**Comment by woodencoder** [comment]
Same issue here

**Comment by chris-redbeed** [comment]
anyone a workaround or solution?

**Comment by zykyan** [comment]
no :(

**Comment by iKols** [comment]
same issue here

**Comment by lkzhao** [comment]
I tried to debug this and found that UIKit added some extra animations to the tabbar's layer.
Think this might be a iOS bug since iOS 11.
Anyway, pushed a workaround in the latest master. let me know if it fixes the issue.
```
  pod "Hero", :git => 'https://github.com/lkzhao/Hero.git', :commit => "a5bec96"
```

**Comment by chris-redbeed** [comment]
Works for me!

**Comment by chris-redbeed** [comment]
I have this Issue again - using version 1.4.0.
I only have this issue when i open a `UINavigationController` onto of a ViewController `.present`
