### ISSUE TITLE
Problem with TabBar size and position on iPhone X after orientation change

### ISSUE THREAD

**Issue by tomasgreen** [HeroTransitions/Hero#358]
Hi!

I've implemented an fullscreen PageViewController to preview pictures. The presenting TabBarViewController only allows portrait mode but the presented PageViewController allows both portrait and landscape. If I change from portrait to landscape at any time while the PageViewController is presented and then dismiss it, the tabbar is reduced to the same size and position as a regular phone (iPhone 8 or whatever).  

This problem does not occur if I remove the hero transitions so I'm gonna go ahead and assume that the problem lies here.

P.S This appears to be a problem when the tabbar's Translucency is set to false

**Comment by beimen** [comment]
I have same issue.

**Comment by Elamuruga** [comment]
I too have the same issue. Could you please fix it soon?
