### ISSUE TITLE
Problem transition between 2 image views with different sizes

### ISSUE THREAD

**Issue by burakkilic** [HeroTransitions/Hero#359]
Hi,

I have 2 view controller. One is with thumbnails of the images, and the other is zoomed version.

When I try to make transition between them, first image is scaled for second image view and quality is not good.

What I need is, after the transition, the larger image is loaded async to the larger imageview.

How can I do that?

**Comment by ckpiggy** [comment]
If you want to async load the larger image 'after' the transition, you can use the callback of `present` in thumbnails controller, for example:
```
let detailVC = DetailViewController()
present(detailVC, animated: true {
    detailVC.loadImage()
}
```
