### ISSUE TITLE
How to simulate Apple Store "Today" feed card selection animation using Hero?

### ISSUE THREAD

**Issue by ramonsgds** [HeroTransitions/Hero#364]
Just by using colors, it would be pretty easy. It's more complicated however, because the destination view controller has text and whatnot. I've been trying but the text gets distorted when scaling to its corresponding text on the destination view controller. Any suggestions?

**Comment by CeceXX** [comment]
You might find this article helpful: 

https://www.phillfarrugia.com/2017/06/19/rebuilding-the-new-app-store-app-today-view/

**Comment by lkzhao** [comment]
Also checkout this example if you want to use Hero for that: https://github.com/lkzhao/AppStoreTransition

**Comment by lkzhao** [comment]
key point is to use `.useNoSnapshot` on the parent view and dont match the child views.
