### ISSUE TITLE
problem with kingfisher lib,

### ISSUE THREAD

**Issue by x1911** [HeroTransitions/Hero#366]
i use kingfisher to load remote image, it works fine

but after import the Hero lib, the Gif file shows only once,

in the seconde time when i open the viewcontroller, which use hero

the gif file didn't show, only a blanc view

**Comment by Au12th0psav** [comment]
me too, hoping to find a solution.

**Comment by lkzhao** [comment]
try using `.useNoSnapshot` on your kingfisher imageView

**Comment by x1911** [comment]
is that right?

```
imgView.heroID = "imgDetail_\(selectedIndex)"
imgView.heroModifiers = [ .useNoSnapshot ]
```

it dosent work ... still the same issue

**Comment by Ekhoo** [comment]
Did you find a solution? I have a similar issue. The transition between placeholder and the fetched image doesn't work anymore because of Hero...

**Comment by kuyazee** [comment]
Can you guys try to pass the downloaded asset to the next view as an optional parameter to use it instead of reloading it again from KingFisher maybe that could work
