### ISSUE TITLE
keyboard constraints bug 

### ISSUE THREAD

**Issue by gregoireLem** [HeroTransitions/Hero#374]
I got  problems with the keyboard constraints only when Hero is enabled : 

For exemple every time I pop then push the same controller : the keyboard appears with an offset that increase on each push : 

![34870926-f79e60ec-f78b-11e7-8ff8-d0eb7f12f51a](https://user-images.githubusercontent.com/31652880/35038488-3fac09c8-fb7b-11e7-8dc9-0209d5dbb1ac.jpg)
![34870930-fa8ea03c-f78b-11e7-8ea0-486a06cff38d](https://user-images.githubusercontent.com/31652880/35038486-3f89a680-fb7b-11e7-90ef-178b43db2b99.png)
![34870932-fca98c6a-f78b-11e7-91f0-01d828f1673b](https://user-images.githubusercontent.com/31652880/35038485-3f65e25e-fb7b-11e7-8fa6-9f139c5e0db4.png)

thanks for helping 🤯

**Comment by romainbiard** [comment]
Having the same problem here

**Comment by isxq** [comment]
So，how to fix it? Does anyone have an idea？

**Comment by gregoireLem** [comment]
Calling myTextField.becomeFirstResponder() in viewDidAppear seems to be a worked for me

**Comment by isxq** [comment]
emmm....I find a method to solve it, before you calling hero.dissmisViewController() or push a other viewController, you should called textfeild.resignFirstResponder() to make sure the keyboard disappeared.

**Comment by kuyazee** [comment]
Just add `self.view.endEditing(true)` on `viewWillDisappear`.
