### ISSUE TITLE
"'shared' is unavailable" error, after pod update

### ISSUE THREAD

**Issue by MinaAshna** [HeroTransitions/Hero#379]
I've updated the 'Hero' pod and the following error has been appeared:
`'shared' is unavailable: Use view controller based solutions where appropriate instead.`

I've also downgrade it to version '1.0.0' but I still have the error.
any idea around the issue?

P.S. the swift version is 4, I've also tried the 3.2 version, and the error is still the same.

**Comment by epitonium** [comment]
I have the same issue

**Comment by kuyazee** [comment]
We're at version 1.5.0 already
