### ISSUE TITLE
How to remove slide effect and keep hero animate when push navigationviewcontroller

### ISSUE THREAD

**Issue by fadielse** [HeroTransitions/Hero#381]
Hi! would u like to tell me How to remove slide effect and keep hero animate when push navigationviewcontroller ?

**Comment by fadielse** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15564979/35326478-6612ef56-0129-11e8-9785-c732d7a44535.gif)

**Comment by lkzhao** [comment]
This is the default animation for navigation controller provided by Hero. To disable the push animation, set self.hero.navigationAnimationType to .fade or .none on the navigation controller.
