### ISSUE TITLE
 UISearchController searchbar doesn't show

### ISSUE THREAD

**Issue by kaich** [HeroTransitions/Hero#387]
* I assign UISearchController to navigationItem.searchController. When I add hero to my UIViewController, searchbar is visible when enter the viewcontroller first time. But at the second time, the searchbar is disappeared. I can't find the reason.
* When searchbar is active, click tableviewCell to push detail Viewcontroller. When I click back button, the animation is so strange. 

Wish somebody replay!

**Comment by lkzhao** [comment]
Sorry, I haven't tested Hero with UISearchController. Hero basically act as a UINavigationController delegate for the UINavigationController. Not sure if apple make them compatible.

**Comment by macfurin** [comment]
Same issue here

**Comment by Hackmodford** [comment]
I have the same problem.
