### ISSUE TITLE
Installation error through pod setup

### ISSUE THREAD

**Issue by mervyn777** [HeroTransitions/Hero#389]
I'm getting the following error when I install/update my pod:

```
Installing Hero (1.0.1)

[!] Error installing Hero
[!] /usr/bin/git clone https://github.com/lkzhao/Hero.git /var/folders/pk/slsyzs1s2b1gltp51058x154tb6g7v/T/d20180205-72847-7jjeyo --template= --single-branch --depth 1 --branch 1.0.1

Cloning into '/var/folders/pk/slsyzs1s2b1gltp51058x154tb6g7v/T/d20180205-72847-7jjeyo'...
error: RPC failed; curl 56 SSLRead() return error -9806
```

My podfile:

```
use_frameworks!
target 'MyApp' do
  #Other pods here
  pod 'Hero', '~> 1.0'
end
```

I'm able to download and install my other pods without any issues. The pod installation process fails only when this pod is added and installed.

**Comment by lkzhao** [comment]
Seems like a network issue. Hero repo is getting pretty big at the moment.

**Comment by AfrozZaheer** [comment]
same here getting same issue.. can install via pod

**Comment by mervyn777** [comment]
@lkzhao So whats the solution to this problem?
