### ISSUE TITLE
Crash on iOS 10

### ISSUE THREAD

**Issue by wassimseif** [HeroTransitions/Hero#390]
I'm getting ` EXC_BAD_ACCESS` when running the app on iOS 10. running on iOS 11 works fine.
Here's the stacktrace : 
![screen shot 2018-02-06 at 2 23 07 pm](https://user-images.githubusercontent.com/7282773/35859611-77260d76-0b49-11e8-8693-80d7a57f090d.png)

When I enable Zombies on the scheme 
Here's what i get just  before the crash

![screen shot 2018-02-06 at 2 22 45 pm](https://user-images.githubusercontent.com/7282773/35859633-8a46ed9e-0b49-11e8-9d93-9460706358bf.png)

**Comment by ranhsd** [comment]
I experience the same issue. I think this is related to the Transition between view controllers

**Comment by wassimseif** [comment]
I solved this by enabling zombies in the scheme. It turned out to be a message sent to a deallocated instance. took me 2 hours to debug this.

**Comment by JoeMatt** [comment]
Sounds like this was external. Closing.
