### ISSUE TITLE
StatusBar while there is the transistion disappears

### ISSUE THREAD

**Issue by pjcau** [HeroTransitions/Hero#392]
Hi Guys, 
before i want to thank to this framework, that it's fantastic and powerfull. I using animate transition from VC1->NV-VC2. Where the VC1, VC2 are UICollectionViewControllers. So when dismiss VC2, and start the animation the controller, the problem is in the status bar that hide as soon as. 

![hero_statutbar_issue_cut](https://user-images.githubusercontent.com/1088176/36087543-2adadbca-0fd3-11e8-908d-70c9541e4c6e.gif)

I tryed to take the view from statusbar and add a hero.id, but don't change nothing.
Can you check this possible issue?
J

**Comment by tooolbox** [comment]
I may be experiencing the same problem here.

**Comment by BryanRyczek** [comment]
I have the same problem. ViewController embedded in a NavController. Background of the status bar goes black during the hero transition, background color reinstated after transition ends.. When I disable Hero, this does not happen.

**Comment by pablogeek** [comment]
@pjcau I'm having the same problem. How did you finally solve this?

**Comment by nharbo** [comment]
I have a similar problem. The status bar gets transparent on back-animation, and then flicks back to the original color afterwards.. Would love a fix!

**Comment by tarekabder** [comment]
I had a similar problem but I changed the modal presentation style of the navigation controller which is presented to full screen and it seems to work for me

let vc = UIViewController90
let nav = UINavigationController(root: vc)
nav.modalPresentationStyle = .fullscreen
self.present(nav, animated: true, completion: nil)
