### ISSUE TITLE
Alpha set to 1.0 during animation while transitioning between controllers

### ISSUE THREAD

**Issue by spifd** [HeroTransitions/Hero#393]
Hi,

I have a transition between 2 controllers and both have their top views alpha set to 0.8. During the transition, the alpha of this view is set to 1.0 while the animation happens and back to 0.8 when done. This also happens with any subviews.

Steps to reproduce:
- Open Hero Xcode workspace
- Edit BasicStoryboard example in HeroExamples subproject
- Set alpha of both VC1 and VC2 main views to 0.2
- Run Basic HeroExamples and use next/back to see the alpha flicking

Any workaround? Thanks.
Cheers,
Fab

**Comment by dudihisine** [comment]
The transitions use a snapshot of your view controller and there is problem with transparent views...
try [this](https://github.com/lkzhao/Hero/issues/344) it worked for me in other problem hope it will work for you as well.
