### ISSUE TITLE
How to use UITabBarControllerDelegate and Hero simultaneously?

### ISSUE THREAD

**Issue by iwheelbuy** [HeroTransitions/Hero#399]
Hello.

When I enabled hero for an `UITabBarController` it stopped calling `UITabBarControllerDelegate` methods like:

```
func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
    //
}
```

The question is: How to use UITabBarControllerDelegate and Hero simultaneously?

**Comment by stefanomondino** [comment]
The main problem seems to be the `HeroTransition+UITabBarControllerDelegate.swift` file.
The original `UITabBarControllerDelegate` gets property stored inside a computed runtime variable (`previousTabBarDelegate`) but it never gets called. I believe a proper working solution could be something like this ```   public func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
    let previousTabBarValue = tabBarController.previousTabBarDelegate?.tabBarController?(tabBarController, shouldSelect: viewController)
    guard tabBarController.selectedViewController !== viewController else {
      return previousTabBarValue ?? false
    }
    if isTransitioning {
      cancel(animate: false)
    }
    return previousTabBarValue  ?? true
  } ```

**Comment by qky1412** [comment]
@stefanomondino I change the pod file according to your codes, but it still doesn't work

**Comment by Z-JaDe** [comment]
```
    public func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        let shouldSelect: Bool
        ...
        tabBarController.hero.isEnabled = true
        Async.main {
            tabBarController.hero.isEnabled = false
        }
        return shouldSelect
    }
```
I don't know if this method is perfect, but this is the way I can think of now.

**Comment by elrond140** [comment]
After messing around with this far too long, I finally have a stupidly simple solution:

1) If you haven't already, ensure your class conforms to UITabBarControllerDelegate:
`class MyTabBarController: UITabBarController, UITabBarControllerDelegate{ ... }`

2) Add the following to viewDidLoad of your MyTabBarController:

        self.hero.isEnabled = false
        self.delegate = self
        self.transitioningDelegate = Hero.shared

I'm now able to call functions like `    func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {...}` without issue

**Comment by yang-shen-wen** [comment]
In your ViewController, implement those delegates.
```swift
    // tabBarController.delegate = self

    func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        // Your logic here
        return Hero.shared.tabBarController(tabBarController, shouldSelect: viewController)
    }

    public func tabBarController(_ tabBarController: UITabBarController, interactionControllerFor animationController: UIViewControllerAnimatedTransitioning) -> UIViewControllerInteractiveTransitioning? {
        return Hero.shared.tabBarController(tabBarController, interactionControllerFor: animationController)
    }

    public func tabBarController(_ tabBarController: UITabBarController, animationControllerForTransitionFrom fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return Hero.shared.tabBarController(tabBarController, animationControllerForTransitionFrom: fromVC, to: toVC)
    }
```

**Comment by aarashgoodarzi** [comment]
@iwheelbuy @qky1412  I had the same issue .The best way is to put your tabBarController in a ViewController as a container. Then setup hero on the container and problem solves.

```
tabBarController.viewControllers = [...]
        let container = UIViewController()
        container.addChild(tabBarController)
        container.view.addSubview(tabBarController.view)
        tabBarController.didMove(toParent: container)
        tabBarController.view.frame = CGRect(x: 0, y: 0, width: container.view.frame.width, height: container.view.frame.height)
        container.modalPresentationStyle = .fullScreen
        container.hero.isEnabled = true
        container.modalAnimationType = .slide(direction: .left)
        rootViewController.present(container, animated: true, completion: nil)
```
