### ISSUE TITLE
Pull to dismiss presented view controller ?

### ISSUE THREAD

**Issue by farshadjahanmanesh** [HeroTransitions/Hero#405]
is there any fast and easy way to implement pull to dismiss a view controller with hero? pull down tableview or scrollView to dismiss presented View controller

and the second question is, can I disable dismissviewcontroller animation? I don't want hero to handle dismiss animation, just want a simple and normal dismiss ...

**Comment by Jauzee** [comment]
@farshadjahanmanesh AFAIK Hero doesn't provide any mechanism to handle actual presenting/dismissing interactions, but it does handle the animation between the views, so you should create a gesture or use scrollView's `contentOffset` property to handle dismissing progress and use `Hero.shared.update(_:)` method to update the animation. You can refer to this article — http://lkzhao.com/2017/02/05/hero-interactive-transition.html 
It's fairly easy to implement interactive animation using Hero.

If you want to disable Hero for _dismissing_ transition, you can just set `self.hero.isEnabled` to `false` and then call `dismiss` method.
