### ISSUE TITLE
Disable any animation of a particular child view programmatically

### ISSUE THREAD

**Issue by gregoireLem** [HeroTransitions/Hero#406]
My child view is being animated because of the parent view animation. How can I disable this for the child view ?

thx

**Comment by lkzhao** [comment]
Just to clarify. Do you want the subview to not move with the superview?

**Comment by lkzhao** [comment]
Just to clarify. Do you want the subview to not move with the superview?

**Comment by gregoireLem** [comment]
Yes exactly

**Comment by gregoireLem** [comment]
Yes exactly
