### ISSUE TITLE
Missing More documentation

### ISSUE THREAD

**Issue by Luisito98704** [HeroTransitions/Hero#410]
I like this library a lot but do not really understand how to make the examples. More documentation or guides please.

**Comment by lkzhao** [comment]
Yes, there is definitely a lack of documentation. And some are outdated as well. I will try to push more tutorials in the coming weeks. Also would love to get some help on the documentations as well.

**Comment by zoka2305** [comment]
I'm using texture aka AsyncDisplayKit and there's no storyboard or xib.
So, I have a little confused to figure out how to apply hero feature to project. It will be better with more code/programmatic examples.

**Comment by antonijap** [comment]
I would like to help you expand documentation because I am trying to use this awesome library and I just can't wrap my head around what code I need to use.

**Comment by kristremblay** [comment]
Any progress on this?  I've been spinning my wheels trying to replicated the "basic" examples in the readme.

**Comment by gloparco** [comment]
Agreed - I have tried to build it, but it looks like there are dependencies that do not exist.
