### ISSUE TITLE
Something conflicting with other animation

### ISSUE THREAD

**Issue by magnaroksjj** [HeroTransitions/Hero#415]
Thank you for amazing pod.
I have not learned programming for a long time. In the learning process, I used 2 pods in my demo app. One is Hero and another is [Ramotion/folding-cell](https://github.com/Ramotion/folding-cell).
I found an issue that confused me a lot. Once I presented a VC with Hero, animation of folding-cell would be a bit weird, some kind of slow and incomplete. The more I present VCs with Hero, the more incompletely folding-cell performs.
I wish to keep using both of this 2 pods but have no idea about what caused the problem totally. I am very sorry for disturbing you. May you give me some guidance. Would there be something wrong with memory releasing or animation conflicting?
Thanks.

**Comment by lkzhao** [comment]
Are you using Hero 1.1.0?

**Comment by magnaroksjj** [comment]
Hero 1.0.1
I installed pods several weeks ago. I will update Hero and test my app again. Thank you very much.

**Comment by magnaroksjj** [comment]
After a day of testing, I failed to find out a solution and decided to give up using Ramotion/folding-cell. LOL
