### ISSUE TITLE
Wrong size while dismissing the video player controller in HeroExamples

### ISSUE THREAD

**Issue by zizicici** [HeroTransitions/Hero#418]
I tested the Interactive Transition in HeroExamples and I found the video view is smaller than image view.

This happened in iOS 11 and iOS 10.

![wrong size while dismissing](https://user-images.githubusercontent.com/1940699/37068522-13e4a670-21ea-11e8-8b9c-41e3f78375f9.png)

If the device is iPhone X, there is a strange white bar in the bottom when I start dismiss the view controller. It seems that it looks like a safe-area related bug.

![strange white bar in the bottom](https://user-images.githubusercontent.com/1940699/37068707-fc984f5c-21ea-11e8-8c23-800cd15166e9.PNG)

**Comment by Arya-Wang** [comment]
i have same issue
