### ISSUE TITLE
Hero 1.1.0 : Unable to set button title programmatically

### ISSUE THREAD

**Issue by alexis-letexier** [HeroTransitions/Hero#419]
Hello there !

I have a weird issue on v1.1.0. When I enable hero on navigation controller animation 

```
 navigationController.hero.isEnabled = true
 navigationController.hero.navigationAnimationType = .none
```

Impossible to set my button title to something (`validateButton.setTitle("Toto Titi", for: .normal)`). It seems keeping my xib button title.

This worked on 1.0.1 and when I disable hero, it's working properly...

Any clue on this ?

Thanks a lot !

**Comment by lkzhao** [comment]
Super weird. I don't think Hero will cause this. In which method are you calling `validateButton.setTitle("Toto Titi", for: .normal)`?

**Comment by Ataraxiis** [comment]
I'm calling it in `viewDidLoad()`. Yes that's super weird but when when I install the previous version (1.0.1), all is working fine and I have my title set...

**Comment by viaszkadi** [comment]
Totally the same issue here.
Both disabling Hero, pressing home button then opening the app again, DispatchQueue.main.async, OperationQueue.current?.underlyingQueue?.async, OperationQueue.main.addOperation solves it, but they should not be needed.

**Comment by Ataraxiis** [comment]
Hello ! I have investigated and I found the commit that's break my UIButton title. 

https://github.com/HeroTransitions/Hero/commit/f1e1add018e88570e3da79cc5ea660899e88820e

If I use the commit before this one, everything is working fine (I have my button title set).

I don't really know why but this is a clue...

Any ideas ?

**Comment by blwinters** [comment]
We are seeing this issue in our project as well. Removing Hero from the project fixes the issue.

**Comment by ibrahimyilmaz7** [comment]
We have same issue too

**Comment by quanzen8labs** [comment]
I have same issue too with version 1.6.2
