### ISSUE TITLE
[Hero 1.1.0][tvOS] navigationAnimationType not work properly

### ISSUE THREAD

**Issue by ghost** [HeroTransitions/Hero#421]
Hi there!
@lkzhao thanks for the great library!

I have faced with the navigation controller transitions issue on tvOS (10/11).
Animation not showing when we using the navigation controller and pushing or pulling some child controller. During the animation, I just see the black color (default color for hero container).

Maybe I'm doing something wrong?

Here is my hero configuration:
```swift
        // MARK: - Navigation controller configuration
        let navigationController = UINavigationController(rootViewController: viewController)
        navigationController.setNavigationBarHidden(true, animated: false)
        navigationController.hero.isEnabled = true
        navigationController.hero.navigationAnimationType = .selectBy(presenting: .zoom,
                                                                      dismissing: .zoomOut)

        // MARK: - First VC configuration
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let viewController = storyboard.instantiateViewController(withIdentifier: "ViewController")
        viewController.hero.isEnabled = true

        // MARK: - Second VC configuration
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let viewController = storyboard.instantiateViewController(withIdentifier: "SecondViewController")
            viewController.hero.isEnabled = true
            
        self.navigationController?.pushViewController(viewController, animated: true)
```

Also, please [check the example project](https://github.com/avitruk/HeroNavigationControllerTest) that shows the issue.

**Comment by piemonte** [comment]
I've encountered the same issue when using multiple fullscreen transparent bg controllers, so I'm just setting the default color to clear in my AppDelegate 

```swift
        Hero.shared.containerColor = .clear
```

**Comment by rubenvde** [comment]
Got the same error too. `Hero.shared.containerColor = .clear` didn't fix the error. But I fixed it by removing the navigation controller and use `self.hero.replaceViewController(with: yourNextViewController)` instead. It's still an annoying bug.
