### ISSUE TITLE
Screen flickers while transitioning

### ISSUE THREAD

**Issue by dudihisine** [HeroTransitions/Hero#423]
i have multiple transitions in my app and all of them flickers since im using the library.

the image is too big i'm sorry but look couple of times please..there is a black screen that flickers just in the start of the transition.

https://i.imgur.com/gMdw9lY.mp4

**Comment by amaurydavid** [comment]
Same issue here on Hero 0.3.6 and iOS 11. It works correctly on iOS 10

**Comment by dudihisine** [comment]
Found a solution to this problem is other issue [here](https://github.com/lkzhao/Hero/issues/344 ).
