### ISSUE TITLE
black background on transition

### ISSUE THREAD

**Issue by canaksoy** [HeroTransitions/Hero#431]
![bug](https://user-images.githubusercontent.com/3260696/37831529-e10d67ee-2eb6-11e8-885f-9047ffce6f67.jpeg)
bug seen on 1.1.0

no bug on 0.3.6

**Comment by dudihisine** [comment]
Try this 
https://github.com/lkzhao/Hero/issues/344

**Comment by Tr736** [comment]
Was this ever resolved?
