### ISSUE TITLE
Swipe back goes to root navigation controller

### ISSUE THREAD

**Issue by thatmarcel** [HeroTransitions/Hero#447]
Hello,
I'm using a view controller in a tab bar controller in a navigation controller.
If I use the swipe back code from the tutorial the back swipe always goes to the root view controller.

Thanks for any kind of help.

**Comment by dmyma** [comment]
@thatmarcel Can you please tell me what behavior do you expect?
->[navC]->[tabBarC]->[VC1], so when you swipe from VC1 it goes to navC, right?
