### ISSUE TITLE
Underlying view disappears when presented modally

### ISSUE THREAD

**Issue by NeverwinterMoon** [HeroTransitions/Hero#452]
I am presenting one controller over another modally using a segue. Without Hero this worked with modal appearing on top of the caller’s view. When I set up Hero, the modal controller’s view is presented but the underlying view is gone and is solid black.

Now I only setup the minimum required to make Hero work - IDs and enabling  destination controller. Do I have to configure  something else as well to make my case work?

Sorry for writing a question here, not sure it’s frowned upon as I saw a couple of people being helped here. 

**Update 01**

It looks like if I set `modalAnimationType = .none` on the presented controller, then I can see the background...

**Comment by NeverwinterMoon** [comment]
I guess, my problem is solved by `modalAnimationType = .none`, but why isn't this on by default when using modal presentation? It is a bit confusing... In my humble option, this should be the default value.

**Comment by kristoft** [comment]
@NeverwinterMoon can you please provide code for your solution? I'm facing the same problem
