### ISSUE TITLE
Slide transition cause a bottom view overlay a top view

### ISSUE THREAD

**Issue by Rotemy** [HeroTransitions/Hero#454]
See video [here:](https://drive.google.com/file/d/1_OFgBTvEWndvqQ1kt7Qepmdj3mqfgVkz/view)

The first view controller:

`
self.navigationController?.hero.isEnabled = true        self.navigationController?.hero.navigationAnimationType = .slide(direction: .left)
`

The bottom image view have the same hero id in the first and second view controllers. The V image is 100% above the bottom image as you can see [here](https://i.stack.imgur.com/H2592.png).

Please help me understand what this happening, I'm dying here.

**Comment by jonahollman** [comment]
@Rotemy I'm having the same issue. Have you solved this?

**Comment by Rotemy** [comment]
> @Rotemy I'm having the same issue. Have you solved this?

Don't remember 🤷‍♂️ didn't touch this project for 2 years
