### ISSUE TITLE
NavigationBar flickers on modal dismiss

### ISSUE THREAD

**Issue by metisdev** [HeroTransitions/Hero#455]
Hello,

Main screen has a tabbar 
Each tab has its own UINavigationController with title
First tab has a photo button to open a modal UINavigationController without title (navigationbar hidden)
When this modal is dismissed with : **viewController.hero.dismissViewController()**

Animation works smooth except presenting viewControllers navigation bar flickers :(

Any suggestions?

**Comment by kalmurzayev** [comment]
Having the same controllers structure and same issue with "blinking" navBar

**Comment by lkzhao** [comment]
https://github.com/HeroTransitions/Hero/issues/235
