### ISSUE TITLE
Navigation Bar modifiers don't effect when push

### ISSUE THREAD

**Issue by pnghitink33b** [HeroTransitions/Hero#459]
I'm custom push transition. 
- in Navigation controller, I set Hero enable = true, navigationAnimationType = .none, set navigation bar modifiers.
- Matched view is worked, but navigation bar don't work.
- I want to to make transition animation in Navigation bar.

**Comment by helimarrabago** [comment]
any update on this? currently experience this

**Comment by helimarrabago** [comment]
any update on this? currently experiencing it
