### ISSUE TITLE
Strange effect on tableview apple store animation

### ISSUE THREAD

**Issue by AndreaMiotto** [HeroTransitions/Hero#463]
Hi I'm trying to replicate the apple store animation, 
I have a table view inside a navigation controller.

I used self.navigationController?.hero.navigationAnimationType = .none

The animation works perfectly for the selected cell, but the rest of the cells, disappears just after the transition. And it's horrible, it's like a delay

What I'm doing wrong?

**Comment by metisdev** [comment]
Hi @AndreaMiotto ,

Did you be able to solve the problem?

Best
