### ISSUE TITLE
Animation Speed/Timing

### ISSUE THREAD

**Issue by hamzakhanfcb10** [HeroTransitions/Hero#464]
First of all, Fantastic Library!

Can you guide me where to control the speed of an animation? Right now it is fast.

Thanks

**Comment by hamzakhanfcb10** [comment]
@lkzhao

**Comment by WeiRujian** [comment]
self.mobileNumTextFeild.hero.modifiers = [.duration(0.8)]

**Comment by WeiRujian** [comment]
`self.mobileNumTextFeild.hero.modifiers = [.duration(0.8)]`
