### ISSUE TITLE
Transition Bug after a while *iPhone X Only* 

### ISSUE THREAD

**Issue by Wolly1985** [HeroTransitions/Hero#468]
Hello first of all I love hero, but I have a problem after a few transitions the transitions start to flicker. that does not happen in the simulator i tested it on an iphone x with ios 11. I thought the bug was only in my app, but in the Hero Example code that happens as well.

This happens approximately after 30-40 transitions.

I once made a video of the bug.

https://www.youtube.com/watch?v=vOX6C0ieKo4

Does anyone have a solution to the problem? 
Current Hero Version 1.2.0

**Comment by Wolly1985** [comment]
I think the problem is in HeroTransition+Start

`      if inNavigationController {
        // When animating within navigationController, we have to dispatch later into the main queue.
        // otherwise snapshots will be pure white. Possibly a bug with UIKit
        DispatchQueue.main.async {
          self.animate()
        }
      } else {
        animate()
      }`

when VC 1 has an Embedded NavigationController and i present Modal a VC 2 than is inNavigationController always false.

i set animate() for a test in Dispatch Block, and i has no flicker problems. But why is this issue only on a iPhone X?

**Comment by lkzhao** [comment]
@Wolly1985 Do you mind checking out the latest Hero, and see if it is fixed for your project?
```
  pod "Hero", :git => 'https://github.com/lkzhao/Hero.git'
```

**Comment by Wolly1985** [comment]
@lkzhao Wow thx works, no flicker on iPhone X :-)

**Comment by fruitcoder** [comment]
@Wolly1985 would you mind closing the issue if it's fixed in the current release?

**Comment by SD10** [comment]
Hey @Wolly1985, we're glad you were able to resolve your issue! I'm going to close this. Feel free to re-open if the problem continues 👍
