### ISSUE TITLE
Card transition into tableHeaderView using Auto Layout

### ISSUE THREAD

**Issue by thexande** [HeroTransitions/Hero#473]
Amazing framework!

I am trying to replicate a card transition from a `UIView` into a `UITableView`'s `tableHeaderView`, and can't seem to get the modifier combinations correct. 

Here is my `UIPanGestureRecognizer`'s target within the table view's header. 
```swift
@objc func pan(gr: UIPanGestureRecognizer) {
        let translation = gr.translation(in: self)
        switch gr.state {
        case .began:
            parentViewController?.dismiss(animated: true, completion: nil)
        case .changed:
            Hero.shared.update(translation.y / bounds.height)
        default:
            let velocity = gr.velocity(in: self)
            if ((translation.y + velocity.y) / bounds.height) > 0.5 {
                Hero.shared.finish()
            } else {
                Hero.shared.cancel()
            }
        }
    }
```

Modifier list for the `Card` subclass of `UIView`:
```swift
       hero.modifiers = [
            .fade,
            .useNoSnapshot,
            .spring(stiffness: 250, damping: 25),
            .autolayout
        ]
        
        hero.id = "card"
```

My basic approach was to create a `UIView` subclass `Card`, enable hero, and add modifiers and the pan gesture. From there, I used the `Card` class within the card view on the `ViewController`(Master) as well as the `tableHeaderView` on the `DetailViewController`(Table with header).  Additionally, I added anchors and text to a label within the card. 

Ideally, this would be an interactive transition between the two instances of the `Card` class. The constraints would change as the transitions happened. Is this possible with your library? 

Additionally, I have added the auto layout extensions mentioned in #305 .

Here is a demo gif of my application, and the source code for this can be found here: https://github.com/thexande/HeroCard/

Thanks in advance for the help!

![hero](https://user-images.githubusercontent.com/7704414/41076786-8b9f1f82-69d0-11e8-8599-62785ba74e8b.gif)

**Comment by gitKun** [comment]
Here you must pay attention to the details of the **xib**;
When creating a `UILabel` using `xib`, `xib` will automatically set the `isOpaque` of `UILabel` to `false`;
But the isOpaque property of UILabel created by **the code** is `true` by default;
There is a judgment on `isOpaque` in Hero's `MatchPreprocessor`, so  you should manually add ` label.isOpaque = false` in your code.

**Comment by gitKun** [comment]
In the 30th line of `Card.swift`, add

```Swift
label.hero.isEnabled = true
```

![修复后的.gif](https://i.loli.net/2020/05/21/rgR7pW5GV2Xe9Bf.gif)
