### ISSUE TITLE
Dismiss snapshot with fade effect

### ISSUE THREAD

**Issue by ManueGE** [HeroTransitions/Hero#475]
Hello! first of all, thanks for this library it works awesome. 

I want to show a view controller that needs to load some content asynchronously from my server. When the transition starts the content is not loaded yet, so some fields (labels, image views, ...) are empty. However, in the middle of the transition the content is received and the UI should be updated. Obviously, the UI is not updated because the transition uses a snapshot with the initial content. Once the transition ends, the updated view replaces the snapshot, which is ok, but I would like to fade that transition (from snapshot to actual view). Is this possible at the moment? Is this something you have in mind to add? I could try to do it if you give me some guidelines. 

Thanks :)

**Comment by ManueGE** [comment]
I fixed the issue this way:

I made my view controller conform `HeroViewControllerDelegate` and added this method:

````
	func heroDidEndTransition() {
		let transition = CATransition()
		transition.type = kCATransitionFade
		transition.duration = 0.25
		view.window?.layer.add(transition, forKey: nil)
	}
````

Anyway,  I'd like to know if there is a better way to do it.

**Comment by iosfitness** [comment]
#491

**Comment by SD10** [comment]
@ManueGE Thanks for sharing how you solved this issue for future Hero users. I'm going to close this but feel free to re-open if the problem continues 👍
