### ISSUE TITLE
failed to render xib and storyboard !

### ISSUE THREAD

**Issue by EdLiya** [HeroTransitions/Hero#483]
![image](https://user-images.githubusercontent.com/15958795/41632916-c88fcc86-746e-11e8-8b7c-38a8618274b3.png)

**Comment by ugenlik** [comment]
add this at the end of your pod file

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end
```

make sure you delete your podfile.lock and pod directory, 

then do a `pod install` again
