### ISSUE TITLE
Duration did not changed if spring HeroModifier was set

### ISSUE THREAD

**Issue by yoxisem544** [HeroTransitions/Hero#484]
I'm trying out HeroExample from github. While I was trying to add some addition modifiers to MatchExample in example project. Like this:
![simulator screen shot - iphone x - 2018-06-20 at 22 15 46](https://user-images.githubusercontent.com/6919999/41664184-b2301860-74d7-11e8-8af0-076a1daa2161.png)
From this:
<img width="558" alt="2018-06-20 10 17 58" src="https://user-images.githubusercontent.com/6919999/41664226-cfe09cea-74d7-11e8-8d4f-4c734cc7f9dc.png">
To this:
<img width="678" alt="2018-06-20 10 18 21" src="https://user-images.githubusercontent.com/6919999/41664256-dfa5f1e8-74d7-11e8-93f9-fd7c6f173226.png">

It says if you set duration modifier, spring modifier won't determine the duration of animation for you.
Duration of the whole animation time is about 16 seconds. I try to look into the code, I figured out that CASpringAnimation had determine the duration time. I couldn't find where duration modifier should override duration time of animation. Is this a bug? Or did I misunderstand something?

Also, .backgroundColor modifier if not working to change backgroundColor of white view from white to yellow. Is this a bug too?

I'm using Hero 1.2.0.

**Comment by lkzhao** [comment]
Right now the spring animation doesn’t support duration modifier. You can control the duration via stiffness

**Comment by yoxisem544** [comment]
Thanks!
