### ISSUE TITLE
Don't rely on "isOpaque" to determine matched view crossfade behavior

### ISSUE THREAD

**Issue by ndonald2** [HeroTransitions/Hero#498]
### Issue

Currently it appears that Hero relies on the `isOpaque` property of matched views to determine whether to crossfade during the transition. This is not obvious without diving into the source code. Furthermore, the official `UIKit` documentation states:

> You only need to set a value for the opaque property in subclasses of UIView that draw their own content using the draw(_:) method. The opaque property has no effect in system-provided classes such as UIButton, UILabel, UITableViewCell, and so on.

Therefore, it seems unreasonable to expect that developers will set `isOpaque` appropriately for views like `UILabel` which are technically non-opaque but where the property has zero effect in `UIKit` itself.

### Suggestion

Instead of relying on the `isOpaque` property, I'd recommend a combination of the following:

1. Add a new `HeroModifier` to force matched views to crossfade (or not crossfade)
2. Automatically crossfade system view classes which one can reasonably assume are not fully opaque within their bounds under the most common use cases (such as `UILabel` which almost always has a clear background). It may also be possible to check the background color in this case
3. Continue using the overall view's `alpha < 1.0` as a way to automatically enable crossfading if no preference is specified

Thank you for considering this suggestion. I can probably put together a PR for this with some guidance. Thanks for making such an excellent library, too -  I absolutely love it!

**Comment by Vinzius** [comment]
I think I encountered a related problem when animating matched views that have kind of semi-alpha background (eg white 0.2) ; and behind there is a gradient background (yeah, kinda bad for calculations :-p) that changes its size during animation. There was no cross-fading I think.

Setting `isOpaque = false` to the main UIView subclass seems to help. But I still need to figure-out some things for subviews (animation isn't perfect yet).

**Comment by ManueGE** [comment]
Adding the `.forceNonFade` modifier works for me.

**Comment by pauloec** [comment]
Gosh, i've spent hours trying to figure out why my UILabel wasn't crossfading.

+1 to this request.
