### ISSUE TITLE
Presenting a view controller modally over current context breaks window hierarchy

### ISSUE THREAD

**Issue by magneticrob** [HeroTransitions/Hero#502]
Hi,

First off, I just wanna say I really like this library - it's a great project. I have discovered an issue however. I have a UITabBar with a series of view controllers in it. In one of these, I have a UICollectionView. Tapping a cell in the collection view presents another view controller, with a hero transition. All works fine.

However, if I set the destination view controller's modalPresentationStyle as .overCurrentContext, I get the animation I want, but upon dismissing, trying to present any _other_ view controllers modally gives me the error "Trying to present x view controller on y view controller whose view is not in the window hierarchy!".

Changing this to .overFullScreen fixes the problem for me though and gives me the effect I want. Changing it to any other modal presentation style fixes the problem without the effect. So it's not a huge issue but it did have me scratching my head for a while, and I thought you might like to be aware that you can potentially break the window hierarchy with this library.

Cheers

Rob

**Comment by FSurani** [comment]
Thank you! This helped with my Issue!

**Comment by michalciurus** [comment]
Same issue, had to change from overCurrentContext to overFullScreen

**Comment by milesquoine** [comment]
Thanks for posting this. We had the same issue. Using overCurrentContext was breaking a side menu library we were using but changing to overFullScreen fixed .it.

**Comment by logansease** [comment]
thanks this also saved me, was about to ditch hero and spend the time doing custom transitions
