### ISSUE TITLE
Crash at HeroTransition+Start.swift

### ISSUE THREAD

**Issue by mvorisis** [HeroTransitions/Hero#504]
I can't be sure if this is the file that crashed because I see the log in Fabric.

This is what I get from crashlytics : 

Title: 
HeroTransition+Start.swift line 37
HeroTransition.start() -> ()

Details:

HeroTransition+Start.swift line 37
HeroTransition.start() -> ()

HeroTransition+UIViewControllerTransitioningDelegate.swift line 0
@objc HeroTransition.animateTransition(using : UIViewControllerContextTransitioning) -> ()

Hope you can figure it out what causes this.

**Comment by 2blane** [comment]
Do you know what version of the cocoa pod you are using. I was on version 0.3.6 for some reason the cocoa pod repo defaulted to the old version. Now I'm on 1.3.0 which has fixed a bunch of bugs. I'm curious to see if this was the issue. I just pushed an update to my app, but it will be a few days before I figure out if the update worked.

**Comment by mvorisis** [comment]
Hi 

Thank you for your answer, I have the latest so I think this isn't the problem.

**Comment by bohachevskyy** [comment]
I have the same issue. @mvorisis Did you manage to fix it?

**Comment by mvorisis** [comment]
@bohachevskyy not yet...

**Comment by Lapinou42** [comment]
Hi, 

Got the same error on Swift 5.1 and last version of HeroTransition.
It appears when using Transition in a TabBar.

![Capture d’écran 2020-01-30 à 15 50 15](https://user-images.githubusercontent.com/3692744/73460144-428e9b00-4378-11ea-90f2-92ed73ad7f47.png)

**Comment by Rcicen** [comment]
Hello, 
I have the same issue. I'm receiving a few different crashes from Hero in my live app. I too receive it in Tabbar transition

Below one seems like it appears only in iOS 10.3.4 users, and it is related with view hierarcy error. But the order of the controllers are correct even if it says its wrong.
![Screen Shot 2020-03-18 at 17 33 55](https://user-images.githubusercontent.com/44670959/76972134-3ae28000-693f-11ea-923d-9a5341c21787.png)

I also get the one on line 53 
![Screen Shot 2020-03-18 at 17 45 11](https://user-images.githubusercontent.com/44670959/76973079-80537d00-6940-11ea-932d-708d9f98bda7.png)
