### ISSUE TITLE
Release new patch version?

### ISSUE THREAD

**Issue by bitwit** [HeroTransitions/Hero#505]
Given the know leak issues in 1.2.0 discussed in https://github.com/HeroTransitions/Hero/issues/432 
shouldn't there be a release fairly soon?

Not sure the current status/stability of master

**Comment by SD10** [comment]
@bitwit Thanks for raising this issue. `master` looks to be stable. It looks like we're not maintaining a CHANGELOG for the library -- so I'll have to look at the latest commits to create a list of changes for the release notes. I will look at this on Sunday

**Comment by SD10** [comment]
Hey @bitwit, I just released a new version, Hero 1.3.0, pending release notes till later though. Let me know if you have any issues upgrading to the new version. Thanks 👍
