### ISSUE TITLE
modifiers .delay is blocking user interaction

### ISSUE THREAD

**Issue by agotfredsen** [HeroTransitions/Hero#511]
Hi. First Love Hero . Its great ..

My issue is this.

I have a view controller with a CollectionView. Lets call it View1 ...
Then I have two buttons lets call them View2 and View3.

some pseudo code:

viewDidLoad() {

view1.hero.isEnabled = true
view.addSubview(view1)

view2.hero.isEnabled = true
view2.hero.modifiers = [.delay(0.5), .fade ... ]
view.addSubview(view2)

view3.hero.isEnabled = true
view3.hero.modifiers = [.delay(1.0), .fade ... ]
view.addSubview(view3)

}

Thing is I want the view2 and view 3 to appear after view1 and the above code do that .. BUT HERO blocks user interactions for the view1 until view3 animation is finished and that I don't want.. is there any parameter or any way to utilise the Hero transition like I done above for all elements but make the view1 (CollectionView) intractable even I view2 and view3 animation hasn't finished ...

**Comment by agotfredsen** [comment]
IT would be great if there where an answer to this ...

**Comment by pavankataria** [comment]
Bump + 1 👍
