### ISSUE TITLE
Hero (1.3.0): .overCurrentContext doesn't show underlying view

### ISSUE THREAD

**Issue by fuxlud** [HeroTransitions/Hero#512]
Hey YiLun,
Thumbs up for this amazing library!

My issue is that I have a black background when transition finished.
This is my code: (maybe I am doing something wrong?)

```
let vc = MyViewController(...)
vc.hero.isEnabled = true
vc.hero.modalAnimationType = .selectBy(presenting: .pull(direction: .left), dismissing: .pull(direction: .right))
vc.modalPresentationStyle = .overCurrentContext
vc.view.backgroundColor = .clear
present(vc2, animated: true, completion: nil)
```

When I set animated property to false 
`present(vc2, animated: false, completion: nil) `
the background is transperent, but then I do not see the transition.

Thanks in advance
Luda

**Comment by LinuleX** [comment]
same here..

**Comment by seboslaw** [comment]
+1

**Comment by seanhamstra** [comment]
+1

**Comment by gaborcsontos** [comment]
+1

**Comment by kristoft** [comment]
Same for `.formSheet`

**Comment by fl034** [comment]
+1

**Comment by darianjug** [comment]
+1

**Comment by Jur4s** [comment]
+1
Hello !
Hero becomes useless in my case with this issue, please give a feedback :)

**Comment by TomQDRS** [comment]
+1

**Comment by kaich** [comment]
+ 1  
Is there any way to fix the bug?

**Comment by SunShineLOL** [comment]
don't use 
```
toVc.modalPresentationStyle = .overCurrentContext
```
use
```
toVc.modalPresentationStyle = .overFullScreen
```
solved my problem

**Comment by Mallenow** [comment]
Hello! In my case .overFullScreen doesn't work with Hero 1.5.0 as well. Does anyone know a solution?

```
 let menuVC = WVMenuViewController.newInstance()
menuVC.modalPresentationStyle = .overFullScreen
menuVC.heroModalAnimationType = .selectBy(presenting: .cover(direction: .right), dismissing: .uncover(direction: .left))
self.present(menuVC, animated: true, completion: nil)
```

The background color of my target VC ist set to .clear. When I change the AnimationType to .fade everything works fine. Unfortunately I need the cover/uncover animation.

Hope someone can help me with this problem.

![Problem](https://user-images.githubusercontent.com/42007592/77444663-6a383780-6dec-11ea-904e-bba05046ab51.gif)

**Comment by davieds** [comment]
+1

**Comment by magicspring** [comment]
I'm getting this too when set clear background color. 

In this case I'm using Navigation Controller inside TabBar. when call pushViewController and pop back to root view and then tap present view it got back screen. 

Hero 1.6.1

` let categoryVC = categoryViewController()`
`categoryVC.hero.isEnabled = true`
`categoryVC.modalPresentationStyle = .overFullScreen`
`self.present(categoryVC, animated: true) {}`

also it got extra UIView as provided images

before pushViewController it work just fine.
![Screen Shot 2564-09-22 at 00 44 35](https://user-images.githubusercontent.com/4918869/134221843-49c87071-7d03-48ea-8207-cd27fc13c3ca.png)

present the  same ViewController after popViewController got two extra UIView.
![Screen Shot 2564-09-22 at 00 46 50](https://user-images.githubusercontent.com/4918869/134222083-943aa547-9c81-4dd0-a211-02707fce67c2.png)

The app show black screen
![IMG_4280](https://user-images.githubusercontent.com/4918869/134222468-efa878aa-9e67-4e77-8478-4f026e66b55a.PNG)

anyone go a solution yet?
