### ISSUE TITLE
Animate a UIView on a CollectionViewCell AFTER transition fails

### ISSUE THREAD

**Issue by FSurani** [HeroTransitions/Hero#517]
I'm doing a very simple transition. My UICollection view is zooming in on present. In the 
`func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell` method I'm adding the modifiers for hero as follows `cell.hero.modifiers = [HeroModifier.scale(0.1)]` 

This works great when I add the `cascase()` modifier to the collectionView as well. 

The problem is that in my Cells `awakeFromNib()` method I have the following lines of code:

```
viewPillbox.transform = CGAffineTransform(scaleX: 0.01, y: 0.01)
        UIView.animate(withDuration: 0.275, delay: 0.5, options: .curveEaseInOut, animations: {
            self.viewPillbox.transform = CGAffineTransform(scaleX: 1.0, y: 1.0)
        }, completion: nil)
```
This animation no matter how much I delay doesn't fire. I understand Hero is an animation Library for transitions so I don't expect it to handle the scale for the UIView ON the collectionview it self, but was wondering if anyone was aware of this bug / issue?

**Comment by pauloec** [comment]
Your awakeFromNib shouldn't handle animations. This is not a bug. You are trying to animate something that hasn't been drawn yet.

**Comment by FSurani** [comment]
@pauloec oh! I see! I suppose it was working before I implemented it and so I was confused. Where do you recommend I put the animation code? It's supposed to fire AFTER the cell is visible.

**Comment by pauloec** [comment]
@FSurani collectionView has a delegate method called `didEndDisplayingCell`. You can tell your cell when to animate.

Apple Doc: https://developer.apple.com/documentation/uikit/uicollectionviewdelegate/1618006-collectionview?language=objc

**Comment by FSurani** [comment]
Thanks! Since this was not a bug I'm going to close it.
