### ISSUE TITLE
Animate a progress bar 

### ISSUE THREAD

**Issue by tryWabbit** [HeroTransitions/Hero#522]
Hello everyone! I'm new to hero just want to ask a question 

I have a progress bar on the top of  view controllers I'm using, lets take a Example

RootVc - > Vc1 -> Vc2 - > Vc3 -> Vc4 - > Vc5 

As we move to Vc1 the progress increase to 20% then Vc2 to 20% and so on.
the problem i'm facing is when i push the view controller the whole progress can be seen moving along with the view controller, So my question is, Is there a way i can animate the bar so it will stay at the same place (right below the navigation bar) and the whole have the natural push animation.

Thanks for your time and wonderful animation library.
Kuldeep

**Comment by Priebe109** [comment]
You need to enable hero on the navigation controller and set the progress bar to have the same hero identifier on all screens
