### ISSUE TITLE
[Bug] Detail navigation controller disabled when searchController is active on parent

### ISSUE THREAD

**Issue by macfurin** [HeroTransitions/Hero#525]
On a tableview controller, when a search controller (iOS 11+) is active (editing), I select a detail row and push a detail view controller, the back button item interaction works as expected and pop detail view controller.
With search controller always active or not, if I select again a detail row, then the back button (or any other button in navigation bar) on detail view controller is disabled : impossible to pop view controller !

When I disable Hero on master's navigation controller, then the problem is gone.

I also observe a strange animation of search bar when popping detail view controller with search controller active and Hero enabled (as mentioned in issue #387 )

I think there is a bug with snapshot on view controller with search bar active.

**Comment by arkilite** [comment]
Same issue here; when I select again a detail row this warning appear in console: "changing items while animating can result in a corrupted navigation bar".
If you set dimsBackgroundDuringPresentation = true on UISearchController the problem is gone.
