### ISSUE TITLE
slight flashing when matching semitransparent views(overlays)

### ISSUE THREAD

**Issue by denysco** [HeroTransitions/Hero#526]
hi,

i'm getting a slight flashing during transition when matching overlays.
i tried it with forceNonFade modifier but it didn't fix the issue.

![overlay](https://user-images.githubusercontent.com/16448244/45223836-5e2a6a80-b286-11e8-9e4e-c37a1a32c79a.gif)

is there a way to fix it or a work around?

**Comment by iamcam** [comment]
I've noticed something similar. Have you tried adding the `forceNonFade` on both views? It appears as if there is a crossfade between the two, however the opacity changes are not perfectly temporally aligned - result being there is a brief period where `A.opacity + B.opacity` is less than 1.0.

In my opinion a crossfade between two matched images should have no visible artifacts so long as the item fit and scale match.

**Comment by agibson73** [comment]
Noticing this as well that the opacity certainly does not add to 1.
