### ISSUE TITLE
Keyboard with transition

### ISSUE THREAD

**Issue by Ignelos** [HeroTransitions/Hero#535]
Hello,

I'm trying to move keyboard along with controller but there is an issue, keyboard wont move... 

![5gjs7](https://user-images.githubusercontent.com/9926919/45709159-fe886500-bb8b-11e8-8fd5-e3331144a18f.png)

**Comment by nmaniatis** [comment]
@Ignasihoo I am having the same issues with the Keyboard. I wouldn't recommend using hero anymore, since I am having more issues-bugs than accepted. @lkzhao What could you do about that ? Do you want a video ?
