### ISSUE TITLE
Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by marwanf1** [HeroTransitions/Hero#536]
Hello,

I can't use Hero in Xcode 10 because it's compiled with Swift 4.1.2

Any plans to release the Swift 4.2 version soon?

**Comment by SD10** [comment]
Hey @marwanf1,

Check out the [swift-4.2 branch](https://github.com/HeroTransitions/Hero/tree/swift-4.2) if you're looking for Swift 4.2 support. Waiting on #534
