### ISSUE TITLE
UILabel Transition from UICOllectionViewCell to ViewController

### ISSUE THREAD

**Issue by Rela2805** [HeroTransitions/Hero#538]
When transitioning UILabel from UICOllectionViewCell to UILabel with different font in another ViewController , label from collectionCell doesn't fade through transition until transition ends.

**I have matched labels with heroID** and I am using UICollectionViewLayout when initialising CollectionView.

Any solutions to this?

![collectioncell issue](https://user-images.githubusercontent.com/26259440/45827645-2cd68380-bcf7-11e8-9358-b0641ce49524.gif)

**Comment by AfrozZaheer** [comment]
Use hero modifier of label .nonSnapshot I think it will help

**Comment by jonahollman** [comment]
> Use hero modifier of label .nonSnapshot I think it will help

Having the same issue transitioning a UILabel from UITableViewCell to ViewController. I tried .useNoSnapshot but it did not work.

**Comment by gitKun** [comment]
As #473 .Please manually set the `isOpaque` of the Black Test to false
