### ISSUE TITLE
Hide contents out of superview bounds in matched view

### ISSUE THREAD

**Issue by ManueGE** [HeroTransitions/Hero#539]
I have a `UIImageView` in one controller. Then, I have a second view controller where I have a `UIView` with a subview `UIImageView`. The second image view is bigger than its superview, but the contents out of the superview bounds are hidden because the superview has `clipToBounds` set to `true`. 

I want to make a transition between the two controllers and both image views have the same `hero.id` so they matches. The transition works ok, but the problem is that the frame of the second image view during the transition is its actual frame and the image "out of bounds" is visible. It becomes invisible again when the transition ends. 

You can see a video here. 

<img src="https://i.imgflip.com/2im4an.gif" title="made at imgflip.com"/>

Any solution for this?

**Comment by ManueGE** [comment]
Obviously, I could set the hero id to the superview instead of the view, but if I do I will lose the optimized snapshot performed in image views, so the transition is not as smooth as I'd like.

**Comment by FSurani** [comment]
No idea, but maybe there is something called "NoSnapshot" which you can try out? I think there is an example on how they do the Apple Cards transition in the examples.
