### ISSUE TITLE
HeroCompatible protocol not visible in Objective-C

### ISSUE THREAD

**Issue by petripartanen** [HeroTransitions/Hero#542]
Hey, thank you for the great library.

I was fixing deprecation warnings in Objective-C code and bumped into `Use hero.isEnabled instead` deprecation warning. Fixing the warning turned out to be challenging as the generated `Hero-Swift.h` doesn't include `HeroCompatible` protocol.

**Comment by CavalcanteLeo** [comment]
Yep 

![captura de tela 2018-09-27 as 13 52 46](https://user-images.githubusercontent.com/1735944/46161730-b4267880-c25c-11e8-8a5f-c1cd2b647bc3.png)

**Comment by Talgat777** [comment]
+1

**Comment by soygalla** [comment]
+1

**Comment by julius94** [comment]
+1

**Comment by CavalcanteLeo** [comment]
Seems no one cares about it

**Comment by CavalcanteLeo** [comment]
@lkzhao any news abut it?

**Comment by peterpaulis** [comment]
+1

**Comment by Asingers** [comment]
+1

**Comment by DanielEdrisian** [comment]
Ok guys, duct-tapey solution here.

If you have an objc class, add a swift extension file which includes @objc methods that the objc class can call. A fully capable Hero is accessible in that Swift file.

Of course, don't forget to add the bridging header and Hero-Swift.h.
