### ISSUE TITLE
Crash: HeroContext.swift line 169 specialized HeroContext.snapshotView(for:)

### ISSUE THREAD

**Issue by dongshuju** [HeroTransitions/Hero#547]
version: pod 'hero', '1.2.0'

Fatal Exception: NSInternalInconsistencyExceptionFailed to create remote render context Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
18 | UIKitCore | -[UIView resizableSnapshotViewFromRect:afterScreenUpdates:withCapInsets:]
19 | Hero | HeroContext.swift line 169specialized HeroContext.snapshotView(for:)
20 | Hero | HeroTransition+Animate.swift line 49HeroTransition.animate()
21 | Hero | HeroTransition+Start.swift line 163HeroTransition.start()
22 | Hero | HeroTransition+UIViewControllerTransitioningDelegate.swift line 0@objc HeroTransition.animateTransition(using:)
23 | UIKitCore | __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
32 | UIKitCore | UIApplicationMain
33 |xxx | main.m line 14main
34 | libdyld.dylib | start

Anyone met same question?

**Comment by dev-xdyang** [comment]
![Screen Shot 2019-10-19 at 5 36 36 PM](https://user-images.githubusercontent.com/7471748/67142799-400ba800-f297-11e9-8d18-dcb68d6e2bf6.png)

Hero version 1.4.0
