### ISSUE TITLE
Example blank screen

### ISSUE THREAD

**Issue by josmanperez** [HeroTransitions/Hero#550]
I'm having troubles to run the examples provided in the source code.. 

## What did you do?

Download the project, run pod install and run Hero Examples target on real device & simulator

## What did you expect to happen?

See the examples in action

##  What happened instead?

White screen

## General Information

* Hero Version: 1.4.0

* iOS Version(s): 12.0

* Swift Version: 4.2

* Devices/Simulators: iPhone 6

* Reproducible in Examples? (Yes/No): No

**Comment by kaishin** [comment]
Same issue here.

**Comment by yosuke1985** [comment]
me too

**Comment by SD10** [comment]
Fixed by #553. Thank you for your patience
