### ISSUE TITLE
Why demo run nothing interface

### ISSUE THREAD

**Issue by fanglinwei** [HeroTransitions/Hero#552]
![5cfd7213-80ff-410e-bd0d-eba511845351](https://user-images.githubusercontent.com/16839723/47251064-57d00680-d460-11e8-98bc-a95894f376c4.png)

运行起来什么都没有

**Comment by fanglinwei** [comment]
...

**Comment by SD10** [comment]
Thanks for opening this @fanglinwei. I didn't know how to update CollectionKit in the example app to version 2.0. So I just commented it out temporarily. I can see you fixed this in #553 👍

**Comment by fanglinwei** [comment]
You're welcome! I really like Hero! It's great
