### ISSUE TITLE
Crash on completeTransition

### ISSUE THREAD

**Issue by Steven4294** [HeroTransitions/Hero#558]
Getting a crash in `line 143 //HeroTransition+Complete.swift`    

```
transitionContext?.completeTransition(finished)
```

I `pod install` and then call `present()`... im running xcode 10.0 and swift 4.2 

The transition properly animates (it looks great!) but then after a couple of seconds it crashes

**Comment by Steven4294** [comment]
![screen shot 2018-11-01 at 5 05 06 pm](https://user-images.githubusercontent.com/8051383/47879956-51df0b80-ddf8-11e8-8326-d565e0eb794a.png)

here is what the `Hero.HeroTransition` looks like upon the crash

**Comment by dannydaddy3** [comment]
How did you resolve the problem?

**Comment by dannydaddy3** [comment]
How did you resolve the problem? @Steven4294
