### ISSUE TITLE
example project doesnot work

### ISSUE THREAD

**Issue by hell4opt** [HeroTransitions/Hero#561]
:(

**Comment by runmad** [comment]
`pod 'CollectionKit', :git => 'https://github.com/SoySauceLab/CollectionKit.git'`

**Comment by chadparker** [comment]
Do a “pod install” and it will work.

**Comment by SD10** [comment]
You may have to run `pod update` if you have an earlier cached version on your machine. Please feel free to re-open if the error persists -- and post the error message, please 👍
