### ISSUE TITLE
[Crash] UIView+Hero.swift line 169 Crash on ios 12.1

### ISSUE THREAD

**Issue by dongshuju** [HeroTransitions/Hero#562]
Those time, we receive lots Crash on 12.1.0, here is the crash log:

 OS Version: 12.1.0 (16B92)

 Device: iPhone 7 Plus

 RAM Free: 51.4%

 Disk Free: 65.2%

0x1accee484 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1acc9b5d#0. Crashed: com.twitter.crashlytics.ios.exception
0  xxx                            0x10035ed14 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  xxx                            0x10035ed14 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  xxx                            0x10035f188 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  xxx                            0x10034e7b0 CLSHandler (CLSHandler.m:26)
4  xxx                            0x10035d27c __CLSExceptionRecord_block_invoke (CLSException.mm:199)
5  libdispatch.dylib              8 _dispatch_lane_barrier_sync_invoke_and_complete + 56
7  xxx                            0x10035ccf4 CLSExceptionRecord (CLSException.mm:206)
8  xxx                            0x10035cb20 CLSExceptionRecordNSException (CLSException.mm:102)
9  xxx                            0x10035c71c CLSTerminateHandler() (CLSException.mm:259)
10 libc++abi.dylib                0x1ac4790fc std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1ac478cec __cxa_rethrow + 144
12 libobjc.A.dylib                0x1ac485c10 objc_exception_rethrow + 44
13 CoreFoundation                 0x1ad23e238 CFRunLoopRunSpecific + 544
14 GraphicsServices               0x1af4b5584 GSEventRunModal + 100
15 UIKitCore                      0x1da4b5054 UIApplicationMain + 212
16 xxx                            0x10027b6d4 main (main.m:14)
17 libdyld.dylib                  0x1accfebb4 start + 4

--

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1ad2b3ea0 __exceptionPreprocess
1  libobjc.A.dylib                0x1ac485a40 objc_exception_throw
2  CoreFoundation                 0x1ad1c9c1c +[_CFXNotificationTokenRegistration keyCallbacks]
3  Foundation                     0x1adcb7140 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x1d9d4b3c4 +[_UIContextBinder createContextForBindable:withSubstrate:]
5  UIKitCore                      0x1d9d4ade0 -[_UIContextBinder _contextForBindable:]
6  UIKitCore                      0x1d9d48e58 -[_UIContextBinder enrollBindable:]
7  UIKitCore                      0x1d9d56250 -[_UICanvas attachWindow:]
8  UIKitCore                      0x1da4e93d0 -[UIWindow _commonInitDebugName:canvas:]
9  UIKitCore                      0x1da4e9e90 -[UIWindow _initWithFrame:debugName:canvas:]
10 UIKitCore                      0x1da4e9b8c -[UIWindow _initWithFrame:debugName:scene:attached:]
11 UIKitCore                      0x1da4ea180 -[UIWindow _initWithOrientation:]
12 UIKitCore                      0x1da4ea1e8 -[UIWindow init]
13 UIKitCore                      0x1da532604 _makeWindowMatchigScreen
14 UIKitCore                      0x1da532eec ___coverScreens_block_invoke
15 UIKitCore                      0x1da532b4c _enumScreens
16 UIKitCore                      0x1da5306d8 _performAfterCommitUnderCoverAllowDefer
17 UIKitCore                      0x1da530ab0 _UISnapshotViewRectAfterCommit
18 UIKitCore                      0x1da9395c8 -[UIView resizableSnapshotViewFromRect:afterScreenUpdates:withCapInsets:]
19 Hero                           0x100950e74 HeroContextfor(_:) (UIView+Hero.swift:169)
20 Hero                           0x100981a40 HeroTransition.animate() (HeroTransition+Animate.swift:49)
21 Hero                           0x100985948 HeroTransition.start() (HeroTransition+Start.swift:163)
22 Hero                           0x1009874b4 @objc HeroTransitionusing(_:) (<compiler-generated>)
23 UIKitCore                      0x1d9e199c4 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
24 UIKitCore                      0x1da4c0cd0 _runAfterCACommitDeferredBlocks
25 UIKitCore                      0x1da4aeccc _cleanUpAfterCAFlushAndRunDeferredBlocks
26 UIKitCore                      0x1da4ddfa0 _afterCACommitHandler
27 CoreFoundation                 0x1ad2437a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
28 CoreFoundation                 0x1ad23e43c __CFRunLoopDoObservers
29 CoreFoundation                 0x1ad23e9dc __CFRunLoopRun
30 CoreFoundation                 0x1ad23e1cc CFRunLoopRunSpecific
31 GraphicsServices               0x1af4b5584 GSEventRunModal
32 UIKitCore                      0x1da4b5054 UIApplicationMain
33 xxx                            0x10027b6d4 main (main.m:14)
34 libdyld.dylib                  0x1accfebb4 start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  xxx                            0x10035ed14 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  xxx                            0x10035ed14 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  xxx                            0x10035f188 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  xxx                            0x10034e7b0 CLSHandler (CLSHandler.m:26)
4  xxx                            0x10035d27c __CLSExceptionRecord_block_invoke (CLSException.mm:199)
5  libdispatch.dylib              0x1accee484 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1acc9b5d8 _dispatch_lane_barrier_sync_invoke_and_complete + 56
7  xxx                            0x10035ccf4 CLSExceptionRecord (CLSException.mm:206)
8  xxx                            0x10035cb20 CLSExceptionRecordNSException (CLSException.mm:102)
9  xxx                            0x10035c71c CLSTerminateHandler() (CLSException.mm:259)
10 libc++abi.dylib                0x1ac4790fc std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1ac478cec __cxa_rethrow + 144
12 libobjc.A.dylib                0x1ac485c10 objc_exception_rethrow + 44
13 CoreFoundation                 0x1ad23e238 CFRunLoopRunSpecific + 544
14 GraphicsServices               0x1af4b5584 GSEventRunModal + 100
15 UIKitCore                      0x1da4b5054 UIApplicationMain + 212
16 xxx                            0x10027b6d4 main (main.m:14)
17 libdyld.dylib                  0x1accfebb4 start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1ace3fed0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace3f3a8 mach_msg + 72
2  CoreFoundation                 0x1ad243bc4 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x1ad23ea60 __CFRunLoopRun + 1396
4  CoreFoundation                 0x1ad23e1cc CFRunLoopRunSpecific + 436
5  Foundation                     0x1adc33404 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
6  Foundation                     0x1adc332b0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 148
7  UIKitCore                      0x1da5a2808 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x1add661ac __NSThread__start__ + 1040
9  libsystem_pthread.dylib        0x1acecf2ac _pthread_body + 128
10 libsystem_pthread.dylib        0x1acecf20c _pthread_start + 48
11 libsystem_pthread.dylib        0x1aced2cf4 thread_start + 4

#2. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1ace3fed0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace3f3a8 mach_msg + 72
2  CoreFoundation                 0x1ad243bc4 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x1axxxd23ea60 __CFRunLoopRun + 1396
4  CoreFoundation                 0x1ad23e1cc CFRunLoopRunSpecific + 436
5  CFNetwork                      0x1ad85f834 -[__CoreSchedulingSetRunnable runForever] + 212
6  Foundation                     0x1add661ac __NSThread__start__ + 1040
7  libsystem_pthread.dylib        0x1acecf2ac _pthread_body + 128
8  libsystem_pthread.dylib        0x1acecf20c _pthxxxread_start + 48
9  libsystem_pthread.dylib        0x1aced2cf4 thread_start + 4

#3. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x1ace3fed0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace3f3a8 mach_msg + 72
2  xxx                            0x1003496b4 CLSMachExceptionServer (CLSMachException.c:180)
3  libsystem_pthread.dylib        0x1acecf2ac _pthread_body + 128
4  libsystem_pthread.dylib        0x1acecf20c _pthread_start + 48
5  libsystem_pthread.dylib        0x1aced2cf4 thread_start + 4

#4. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1ace3fed0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace3f3a8 mach_msg + 72
2  CoreFoundation                 0x1ad243bc4 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x1ad23ea60 __CFRunLoopRun + 1396
4  CoreFoundation                 0x1ad23e1cc CFRunLoopRunSpecific + 436
5  AVFAudio                       0x1b324660c GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x1b3272768 CAPThread::Entry(CAPThread*) + 88
7  libsystem_pthread.dylib        0x1acecf2ac _pthread_body + 128
8  libsystem_pthread.dylib        0x1acecf20c _pthread_start + 48
9  libsystem_pthread.dylib        0x1aced2cf4 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x1ace4bb9c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1aced0100 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0x1aced2cec start_wqthread + 4

#6. Thread
0  libsystem_kernel.dylib         0x1ace4bb9c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1aced01c0 _pthread_wqthread + 540
2  libsystem_pthread.dylib        0x1aced2cec start_wqthread + 4

#7. Thread
0  libsystem_pthread.dylib        0x1aced2ce8 start_wqthread + 190

#8. Thread
0  libsystem_kernel.dylib         0x1ace4bb9c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1aced0100 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0x1aced2cec start_wqthread + 4

#9. Thread
0  libsystem_pthread.dylib        0x1aced2ce8 start_wqthread + 190

#10. Thread
0  libsystem_pthread.dylib        0x1aced2ce8 start_wqthread + 190

**Comment by dongshuju** [comment]
Anyone has the same Crash

**Comment by clbemre** [comment]
ı have same error for TestFlight

**Comment by jarigo1984** [comment]
Yep, I have the same crash

<img width="1023" alt="screenshot 2019-02-13 at 19 27 50" src="https://user-images.githubusercontent.com/26749118/52738458-9cab1a80-2fc6-11e9-9364-ac7cfcb81153.png">

Anyone found progress with this?
