### ISSUE TITLE
ViewController can't be deinit by using Hero in specific way

### ISSUE THREAD

**Issue by mml237** [HeroTransitions/Hero#563]
## What did you do?

I find that when I have a BaseNavigationController and set it's delegate = itself,
then I present the second controller in this way: 
let navi = BaseNavigationController(rootViewController: secondVC())
        navi.modalPresentationStyle = .overFullScreen
        navi.hero.isEnabled = true
        firstVC.present(navi, animated: true, completion: nil)
after dismiss the secondVC, it can not be deinit ~

please see my example below, best wishes for you !

## What did you expect to happen?

 the secondVC deinit method could be excuted 

##  What happened instead?

 the secondVC deinit method could not be excuted

## General Information

* Hero Version:
1.3.0
* iOS Version(s):
iOS 12.0
* Swift Version:
4.0
* Devices/Simulators:
iPhone6sp
* Reproducible in Examples? (Yes/No):
Yes

**Comment by alvincrisuy** [comment]
Have you fixed your problem?
