### ISSUE TITLE
Laggy animation and presentation

### ISSUE THREAD

**Issue by GokmenAkar** [HeroTransitions/Hero#565]
## What did you do?
I tapped the cell to open the viewController. 
## What did you expect to happen?
I expected to see the opening animation properly. 
##  What happened instead?
It opened slowly, and with lag. 
## General Information
I configured hero successfully, there are several collectionViews and a long scrollView with infinite scroll. I have 2 requests in the detailViewController(which is what I try to open properly)

* Hero Version: 1.4.0

* iOS Version(s): 12.1

* Swift Version: 4.2

* Devices/Simulators: iPhone 5s, iPhone 6 (Real Device) / iPhone SE, iPhone 6, iPhone X (Simulator)

* Reproducible in Examples? (Yes/No): No

## Demo Project

I'll provide it as soon as possible.

**Comment by lexuanquynh** [comment]
I have a same issue. please help me get a reason?

**Comment by disczteam** [comment]
Having the same issue
