### ISSUE TITLE
it wont work if statically linked 

### ISSUE THREAD

**Issue by own2pwn** [HeroTransitions/Hero#570]
I've added sources to my project, set target type to `static` library, tried to perform transition and this way Hero won't work. After compiling as dynamic library it worked as expected. 

Is there a way to use Hero statically linked?

**Comment by Reflejo** [comment]
This is sadly a known swift bug when linking static libraries with extensions. You can fix this issue by doing `-force_load <path>/Hero.framework/Hero`

**Comment by JoeMatt** [comment]
Workaround. Upstream big.
