### ISSUE TITLE
Hero Modifier not working when presenting navigation controller with ViewController

### ISSUE THREAD

**Issue by kaungsoe** [HeroTransitions/Hero#573]
I try to modally present a navigation controller which has one ViewController. In one of the subview of that ViewController, I set hero modifier but when VC is presented, the modifier is not working but when it's dismissed it's working.

## What did you expect to happen?

Modifier should be working when presenting.

##  What happened instead?

Modifier is working when VC is dismissed but not when presented. 

## General Information

* Hero Version: 1.3.0
 
* iOS Version(s): 12.1

* Swift Version: 4.2

* Devices/Simulators: simulator iPhone XR

**Comment by chandraf22** [comment]
Having the same issue. Do you have any ways to do this?

**Comment by burakakyalcin** [comment]
did you enable hero on navigation controller?

**Comment by kuyazee** [comment]
Is your issue like this?

```
vc1 presents nv1(root: vc2)
```

Because I'm also looking for a way to have a transition animation for this scenario

**Comment by kaungsoe** [comment]
@kuyazee yes the same issue.

**Comment by gutoboranga** [comment]
same issue here :(
any updates?

**Comment by wolfej94** [comment]
Any solution for this?

**Comment by AAAstorga** [comment]
Set `isHeroEnabled = true` on your navigationController fixed it for me
