### ISSUE TITLE
No transition from Tableview to Viewcontroller

### ISSUE THREAD

**Issue by Wizzel1** [HeroTransitions/Hero#575]
## What did you do?
I have a StreamViewController where 2 ContentViewControllers are Displayed with a PageControl.

I did set my imageview.hero.id on both ContentViewController and DetailViewController to "recipeimage"
I did set "is Hero enabled" on both viewcontrollers to "On"

My ViewControllers :
<img width="477" alt="bildschirmfoto 2019-01-25 um 11 40 50" src="https://user-images.githubusercontent.com/43343510/51741072-1f127f80-2096-11e9-821b-96f193420b57.png">

Code for configuring each individual cell inside the ContentViewController:
<img width="632" alt="bildschirmfoto 2019-01-25 um 11 37 53" src="https://user-images.githubusercontent.com/43343510/51740935-c216c980-2095-11e9-814b-420fadd8c2fc.png">

Code for configuring the imageview of the DetailViewController:
<img width="609" alt="bildschirmfoto 2019-01-25 um 11 39 37" src="https://user-images.githubusercontent.com/43343510/51741014-f4282b80-2095-11e9-8369-d549db78404d.png">

## What did you expect to happen?

I was expecting an animation during the transition from my tableview to the DetailViewController

##  What happened instead?

There was no animation, the transition was the same as always.
(I am using a simple "show" segue.)

**Comment by pareekkhushboo77** [comment]
Hi found any solution ? please share?

**Comment by PatrickAdams** [comment]
If your view controllers are embedded in a UINavigationController you need to set hero.isEnabled on the navigation controller as well. Hope that helps!

**Comment by Wizzel1** [comment]
Thanks Patrick, but still no transition. I am wondering if hero interferes with another Framework.
