### ISSUE TITLE
Disabling hero for dismissal causes the screen to freeze

### ISSUE THREAD

**Issue by michalciurus** [HeroTransitions/Hero#581]
## What did you do?

I have a pretty nonstandard use-case where I need to use a custom (my own) `UIViewControllerAnimatedTransitioning` for performance reasons.

I want to use hero for presentation:

```
 hero.isEnabled = true
```

and after presentation I set:

```
self.transitioningDelegate = self
hero.isEnabled = true
```

## What did you expect to happen?

I expect presentation to be handled by Hero and dismissal by my own custom `UIViewControllerAnimatedTransitioning` class.

##  What happened instead?

Everything worked but in the end after the dismissal the screen freezes because there seems to be an invisible `SnapshotWrapperView` on top of the view hierarchy.

## Discussion

I'm using `modalPresentationStyle = .overFullScreen` which seems to cause the problem - when I remove it everything works fine.

So it leads me to believe that it's expected behavior. When I remove `storedSnapshot` from `toVC` after custom dismissal is finished everything works fine.

Do you think Hero should support this case or not? Thanks :)

**Comment by otymartin** [comment]
@michalciurus how did you solve this?

**Comment by sekny** [comment]
Hi @michalciurus, can you show me how you remove that `storedSnapshot` from `toVC`?
