### ISSUE TITLE
Dismissing/Unwind Presented ViewController

### ISSUE THREAD

**Issue by KNG-Dev** [HeroTransitions/Hero#586]
How do you dismiss a presented ViewController that doesn't have a navController?

So this is my FirstViewController:

`func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {  
       let heroViewController = HeroViewController()
        heroViewController.hero.modalAnimationType = .zoom
        hero.replaceViewController(with: heroViewController)
    }`

SecondView Controller: I created button and added this button. handleDismiss is being hit but nothing happens.

`@objc fileprivate func handleDismiss() {
        hero.unwindToRootViewController()
    }`

**Comment by KenOfHearts** [comment]
I also tried hero.dismissViewController() and that also doesn't work.
