### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by bettola** [HeroTransitions/Hero#588]
Hi there,
when the next version is supposed to be released? 

There are a good numbers of issues to be fixed and it seems there have been no commits since last year.

Thanks anyway for the hard work.

**Comment by shuoli84** [comment]
@SD10 @lkzhao Could you guys pls shed some light on this? What is the future plan, or maybe it's time to involve more maintainers? Thx in advance.

**Comment by JoeMatt** [comment]
Release 1.5.0 is under peer review
