### ISSUE TITLE
Is there a way to use a custom UIPresentationController?

### ISSUE THREAD

**Issue by bryan1anderson** [HeroTransitions/Hero#596]
I'm using a slide over transition 
`nav.hero.modalAnimationType = .selectBy(presenting: .cover(direction: .left), dismissing: .uncover(direction: .right))`
However, I need the presented view controller to only be visible over a portion of the screen. I would use a UIPresentationController to handle this normally, but I can't find any documentation to override hero transitions and provide this functionality.

Is it possible? Perhaps using a different method?

**Comment by InsectQY** [comment]
Like this?
![IMG_0242 TRIM](https://user-images.githubusercontent.com/22448409/57514792-c4025100-7343-11e9-9a92-ff89a1232e36.gif)

**Comment by xuxueing** [comment]
yes ,i want this, how do it
