### ISSUE TITLE
Question: should I use just animation without present, push, modal..etc.. transition controller?

### ISSUE THREAD

**Issue by XOneto9** [HeroTransitions/Hero#598]
Hi, I'm David
and I use a Hero module. it is awesome and beautiful animator!!
Just curious about animation.
I mention above title that it is using only animation with heroModifier without viewController transition?

I know the hero module has referenced Motion related to Matarial module. but the Motion is possible to using animation like as move, scale, delay, etc..
So, how about hero? if it possible, I wanna know that!!

**Comment by shuoli84** [comment]
Probably not, the lib is built on top of ViewController transitions. It is different area with UIView animation.

**Comment by raulferrer** [comment]
I don't know if this can solve your problem, but in  [Hero Wiki] (https://github.com/HeroTransitions/Hero/wiki/Usage-Guide) you can find some modifiers that could do what you are asking for.
