### ISSUE TITLE
Screen freezes if fast make push<->pop

### ISSUE THREAD

**Issue by EgorkZe** [HeroTransitions/Hero#599]
HI! I found the issue when I make push<->pop transition. I tried to insert block with pop call to main.async closure but it did not help. Maybe someone have already found solution and can share with me?

**Comment by Maxim-Zakopaylov** [comment]
Are you duplicated this issue https://github.com/HeroTransitions/Hero/issues/572 ?

**Comment by jensonjohn001** [comment]
same problem..

**Comment by kuyazee** [comment]
Closing issue since this is a duplicate of #572
