### ISSUE TITLE
REQUEST: Improve documentation 

### ISSUE THREAD

**Issue by fbarraganef** [HeroTransitions/Hero#602]
I think that is required create documentation for every funcionatlity and use case where Hero can works or not. 

Now, everything that we can use with Hero is guessing and testing, but there is not a way  where you can find a complete guide of use and implementation, only the github readme and the examples that is completely useless for someone that is learning to use the library from zero and learning iOS development. 

It's a shame that Hero is a great library with awesome functionality, but with a poor attention to this kind of details, related to the documentation, this is very important point in my opinion, and it will help to avoid a lot of issues asking a lot questions related to how implement something or why is happening something. 

Thanks,

**Comment by bendytree** [comment]
Yes - I agree. I was confused on whether a nav controller needed a delegate, whether children controllers needed to be enabled, etc. Plus a lot of examples are out of date. Something like this would have been nice:

###  UINavigationController Example

    import Hero
    
    let navigationController = UINavigationController(...)
    navigationController.hero.isEnabled = true
    navigationController.hero.navigationAnimationType = .zoomSlide(direction: .up)
    
In any case, great library!

**Comment by JoeMatt** [comment]
Closing. Release 1.5.0 has updated jazzy docs. New tickets and prs can be opened to document specific gaps since a general “better docs” is too large a scope for a single issue ticket (if only GitHub had epics)
