### ISSUE TITLE
Transfer AVPlayer to another view controller

### ISSUE THREAD

**Issue by sevgjan** [HeroTransitions/Hero#604]
I'm having an issue transfering the avplayer in another view controller, when transition finishes video player is paused, if I play it again, it starts a little bit then the video freezes and sound goes on still.

Example:
VC1:
videoView.hero.id = "video"
and before presenting vc2, i pass AVPlayer to VC2

VC2:
playerContainer.hero.modifiers = [.source(heroID: "video")] 
or playerContainer.hero.id = "video"

I also tried useNoSnapshot option, but it didn't work, after transition the AVPlayerView is white.
Is there a way to solve this issue? After transfering avplayer to another view controller, so it continues playing, similar to AppStore Card approach.

Thanks

**Comment by dannydaddy3** [comment]
Did you resolve this problem with video?

**Comment by dannydaddy3** [comment]
Did you resolve this problem with video? @sevgjan

**Comment by sevgjan** [comment]
@dannydaddy3
This helped me:
https://twitter.com/skumancer/status/294605708073263104?lang=en

Then I transferred avPlayer to the destinationVC and destroyed it as suggested, and when dismissed a view, transferred it back via delegate method. it worked. 

If not, also try the suggested .useNoSnapshot from the Hero example itself.

**Comment by dev-xdyang** [comment]
Add AVPlayer to a container view, use .useNoSnapshot to transform the container view, I get a smooth animation and doesn't effect the AVPlayer's playing. If the AVPlayer size is different in two ViewController, you can combine .scale and .position(move container center) to get best effect.

**Comment by phantomato** [comment]
@sevgjan, @dev-xdyang Have you guys managed to have it working? All my effort comes to having the AVPlayerLayer not catching up with it's  own view's frame
