### ISSUE TITLE
UINavigationController root view with hero transition

### ISSUE THREAD

**Issue by patthehuman** [HeroTransitions/Hero#605]
I have a view controller which has a CollectionView. 

The CollectionView cells VIEW property has my hero ID for my view controller.

I place the view that contains my CollectionView inside of a UINavigationController.

If I present (using self.present) the collectionview cell hero ID works and there is a nice animation.

If I place the view containing my collectionview inside of a UINavigationController as "rootViewController" then the Hero animation does not work any longer.

**Comment by KRUBERLICK** [comment]
Try setting `hero.isEnabled` for the root `UINavigationController`

**Comment by patthehuman** [comment]
@KRUBERLICK i did that and it still doesnt work
