### ISSUE TITLE
Is project depreciated?

### ISSUE THREAD

**Issue by EmreSURK** [HeroTransitions/Hero#606]
Still maintaining?

**Comment by jyounus** [comment]
Looks like it has been abandoned by the maintainers (I don't blame them, OSS takes a lot of someone's personal time). Probably a good idea for someone to fork and maintain the project, if they are willing to put the time in.

**Comment by alexanderkhitev** [comment]
Hey @SD10 ! Any news?

**Comment by kuyazee** [comment]
Bump, consider adding more maintainers.

**Comment by chrisscholly** [comment]
Bump

**Comment by momamene** [comment]
Bump

**Comment by lkzhao** [comment]
#617

**Comment by JoeMatt** [comment]
Closing. New discord and maintainers in above linked issue
