### ISSUE TITLE
HeroCoreAnimationViewContext.swift line 42

### ISSUE THREAD

**Issue by gouravgupta72** [HeroTransitions/Hero#608]
## What did you do?

We had used latest library to add card transition animation

## What did you expect to happen?

In our production app we are getting following crash

HeroCoreAnimationViewContext.swift line 42
 CALayer.hero_add(anim:forKey:)

## General Information

* Hero Version:
1.4.0

* iOS Version(s):
12

* Swift Version:
3.0

* Devices/Simulators:
iPhone x/ XS

* Reproducible in Examples? (Yes/No):
No

**Comment by dev-xdyang** [comment]
I encounter the same crash, I guess it's because force unwrapping in some case.

**Comment by dev-xdyang** [comment]
this crash be fixed at pull request #653 . this issue can be closed @gouravgupta72  @iDevid
