### ISSUE TITLE
HeroContext Crash

### ISSUE THREAD

**Issue by iDevid** [HeroTransitions/Hero#612]
The superview here is force unwrapped and causes a crash in some cases.

https://github.com/HeroTransitions/Hero/blob/faf8475a7a0b2f211101ef3deb7ad4bd5534d725/Sources/HeroContext.swift#L227

**Comment by pablogeek** [comment]
How is the status of this?

**Comment by iDevid** [comment]
Should be fixed with this pr
 #634
