### ISSUE TITLE
iOS 13, Page Sheet modal controller incorrect display.

### ISSUE THREAD

**Issue by StasanTelnov** [HeroTransitions/Hero#614]
## What did you do?
I add Hero library to my project, set `isHeroEnabled` on ViewControllers and set `HeroID` on views.
Add new modal controller with `Page sheet`.

## What did you expect to happen?
I expect to happen views modification and transform on transition. In iOS 11-12 - all OK.
And I expect to happen in iOS 13, that I can see my modal view controller with default ios 13 dismiss swipe, top rounded and over previos view controller.
Something like this: https://prnt.sc/patp70

##  What happened instead?
But in iOS 13, I happened this: https://prnt.sc/pato7j
And swipe down for dismiss dont work.
This problem fixed, if I change presentation style to `Full screen`. But I want `Page sheet` presentation style.
How I can fix this?

## General Information

* Hero Version:
1.4.0

* iOS Version(s):
iOS 13.0

* Swift Version:
5.0

* Devices/Simulators:
Simulator iPhone 11

**Comment by michalciurus** [comment]
@StasanTelnov is the vc you're presenting a navigation controller? I have the exact same problem specifically with nav vcs.

**Comment by StasanTelnov** [comment]
@michalciurus, yes, I presenting a navigation controller.

**Comment by michalciurus** [comment]
looks like we'll have to fix it ourselves

**Comment by michalciurus** [comment]
https://github.com/HeroTransitions/Hero/issues/181

Might be connected to the fact that Hero doesn't support .pageSheet

**Comment by rezwan-islam** [comment]
Hero doesn't support .pageSheet
Set the "Presentation" property of the navigation controller to "Full Screen".

**Comment by joeljfischer** [comment]
It seems to _kind_ of support `.automatic` but it's really buggy.

**Comment by patthehuman** [comment]
FullScreen works but it performs buggy due to the new presentation style from Apple

**Comment by sashakid** [comment]
+1, the same for me, strange black bar at the top of the screen, but I'm using         
`present(controller, animated: true, completion: nil)` with hero enabled.

**Comment by CentrumGuy** [comment]
> +1, the same for me, strange black bar at the top of the screen, but I'm using
> `present(controller, animated: true, completion: nil)` with hero enabled.

This is probably because your view controller presentation style is set to ".automatic", ".pageSheet", or ".formSheet". These presentation styles changed with the transition to iOS 13 and Hero is not yet optimized to handle them. Set your view controller's presentation style to ".fullScreen" in order to present it as you did in iOS 12 and earlier.

**Comment by sashakid** [comment]
> Set your view controller's presentation style to ".fullScreen"
Forgot about that, thanks a lot, it helped 👍

**Comment by thorstenstark** [comment]
Any progress on this topic? We also have problems working with modal view controllers.
Is support for `.pageSheet` and `.formSheet` planned at all?

**Comment by hardiktgreydesk** [comment]
Any progress on this issue? i am facing same issue strange black bar at the top of the screen.

**Comment by quintus-luis** [comment]
I have the same issue. It would be absolutely great if Hero would also support this type of modal styles...

**Comment by greyfruit** [comment]
remove transitioning delegate just after enabling hero, that's worked for me
`navigationController.hero.isEnabled = true
  navigationController.transitioningDelegate = nil`

**Comment by philipbel** [comment]
> remove transitioning delegate just after enabling hero, that's worked for me
> 
> ```
> navigationController.hero.isEnabled = true
> navigationController.transitioningDelegate = nil
> ```

This seems to work on iOS 13.5. Cheers.

**Comment by nobre84** [comment]
> remove transitioning delegate just after enabling hero, that's worked for me
> 
> ```
> navigationController.hero.isEnabled = true
> navigationController.transitioningDelegate = nil
> ```

Does this work around work for anyone still on iOS 14 ? I'm presenting a VC that is not on a Navigation hierarchy with formSheet, and any of the hero transitions done on that app previously make it break
