### ISSUE TITLE
Help wanted.

### ISSUE THREAD

**Issue by lkzhao** [HeroTransitions/Hero#617]
As you can see this project isn’t maintained very well. There are a lots of opening issues and PRs not being reviewed.

Hero has its good times but now it has become quite outdated and cumbersome to work with. 

And both me and @SD10 are quite busy with our life work and cannot find enough time to get this project up to pace. 

So I guess we have two choices here:
1. Deprecate the project.
2. Find contributes that would like to take on Hero.

If you are still using the project, Great! Help us and others by becoming a contributor please. If we don’t find enough people then I will just deprecate the project for good.

Comment below if you want to become a contributor and i will add you as one.

**Comment by kuyazee** [comment]
I'm game for this, but I need a few others who are willing to help support an open source project as huge as this.

**Comment by iDevid** [comment]
Here I am :)

**Comment by mikehobi** [comment]
I would like to support an any way I can as well.

**Comment by brandonminch** [comment]
I have used Hero in the past and it is hands down one of my favorite open source projects. I was about to implement it into a new project and was sad to see it is on the verge of deprecation. I would love to contribute however I can!

**Comment by kuyazee** [comment]
This is wholesome

**Comment by iDevid** [comment]
@lkzhao what do you think?

**Comment by JoeMatt** [comment]
By contributors do you mean maintainers? 

ie; 

access to approve pull requests?
release delivery?
project administration?

There's a number of PR's waiting for approval, so there are already contributors in that regard. It sounds like maintainers are required, no?

**Comment by lkzhao** [comment]
Yes, I meant maintainers to handle issues and PR requests. Also do project planning and release.

Sounds like there are still interest in keeping this project alive.

Going to send out collaborator invites today to all of you guys. Let’s also create a chat room to talk, what message app do you guys prefer?

**Comment by kuyazee** [comment]
I suggest slack

> Going to send out collaborator invites today to all of you guys. Let’s also create a chat room to talk, what message app do you guys prefer?

I suggest slack, we can also start a community starting from there.

**Comment by JoeMatt** [comment]
My organization is considering Hero as the base implementation for a markup defined animations/transitions DSL.

@lkzhao You can +1 me on a maintainer, and if we go a different direction and I don't have the time for a non-business project I can always step down.

Thanks.

**Comment by JoeMatt** [comment]
> > Going to send out collaborator invites today to all of you guys. Let’s also create a chat room to talk, what message app do you guys prefer?
> 
> I suggest slack, we can also start a community starting from there.

Or a Discord. I moved my FOSS App's community over from Slack due to limitations of having a public/private set of channels.

Perhaps Slack has improved its feature set for ad-hoc non-commercial domains but Discord seems more popular of the two. A few of the projects I commit to as well use it, reicast, libretro.

**Comment by lkzhao** [comment]
Alright guys, Lets do this!

Slack needs to setup a invite page in order to work.
So I setup a discord server here: https://discord.gg/xbADF2f

**Comment by pauloec** [comment]
Still open for contributors? I'm willing to help!

**Comment by nick-potts** [comment]
Just wanted to pitch in and say how excited I am to see this project back from the dead - there's nothing quite like it.
