### ISSUE TITLE
SwiftUI

### ISSUE THREAD

**Issue by lvnkmn** [HeroTransitions/Hero#623]
## What did you do?

I tried to find out if Hero would work in combination with SwiftUI

## What did you expect to happen?

I actually expected it would not work.

##  What happened instead?

It turned out to work out of the box.

## General Information

* Hero Version: 1.4.0

* iOS Version(s): 13

* Swift Version: 5

* Devices/Simulators: iPhone X

* Reproducible in Examples? (Yes):

## Demo Project

https://github.com/CuratoOpenSource/Hero-SwiftUI-example

**Comment by lvnkmn** [comment]
So yeah, against my expectations Hero turned out to work with SwiftUI, since I did not see this documented here I thought this would be worth mentioning.

The demo project that's linked above should show that Hero can be quite easily be used with the new framework.

Since this is not really an issue anymore I'll close it and leave it be for documentation purposes.

Hope this helps!

**Comment by iDevid** [comment]
Thank you for the letting us know! This is very interesting 👍

**Comment by kuyazee** [comment]
Hey @lvnkmn would be great if you could create a PR to add your example maybe to the examples folder

**Comment by lvnkmn** [comment]
@kuyazee sure, I’ll take some time for this on Friday 👌.

**Comment by lvnkmn** [comment]
Sorry, something came up so I could not do this on Friday. 

However I started making an appropriate example this evening and will likely create the PR.

**Comment by lvnkmn** [comment]
Forgot to close this one.
