### ISSUE TITLE
Hero enabled on UINavigationController with hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by zra95** [HeroTransitions/Hero#624]
I enable hero on my `navigationcontroller` wish is embed in a `tabbarcontroller`.

To use hero animation on my child controller who is pushed on the `navigationcontroller`, I enabled hero on the `navigationcontroller` and set a fade `navigationAnimationType`. 

But when I push a controller, I need to hide my tabbar and set `hidesBottomBarWhenPushed` true on the pushed controllers.

But this is a strange animation, the `tabbar` stay in position, and when the transition to the new controller finished, the `tabbar` disappear, without animation.

And for the back action, the tabbar still invisible until the transition finished (so there is a background colour of my child view until the tabbar appear).

My question is:

Can I make an animation during the hero transition to make the tabbar disappear, like a translate animation.

Last version of Hero, iOS 13, swift 5.

Thank you !

**Comment by RadhikaMV-Philips** [comment]
Hey Even I have the same issue. Did you find the solution for it ?

**Comment by jordanpwood** [comment]
I have also run into this problem, is there a solution to it?

**Comment by jglez-zz** [comment]
Add a snapshot of tabBar do the trick

`    func navigationController(_ navigationController: UINavigationController, animationControllerFor operation: UINavigationController.Operation, from fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        if let transition = Hero.shared.navigationController(navigationController, animationControllerFor: operation, from: fromVC, to: toVC) {
            if toVC.hidesBottomBarWhenPushed, !fromVC.hidesBottomBarWhenPushed, let tabBar = self.tabBarController?.tabBar {
                tabBarSnapshot?.removeFromSuperview()
                if let snapShot = tabBar.snapshotView(afterScreenUpdates: false) {
                    tabBarSnapshot = snapShot
                    fromVC.view.addSubview(snapShot)
                    snapShot.snp.makeConstraints({ (make) in
                        make.leading.equalToSuperview()
                        make.trailing.equalToSuperview()
                        make.bottom.equalToSuperview().offset(snapShot.bounds.height)
                        make.height.equalTo(snapShot.bounds.height)
                    })
                    tabBar.alpha = 0
                }

            } else if !toVC.hidesBottomBarWhenPushed, fromVC.hidesBottomBarWhenPushed, let tabBar = self.tabBarController?.tabBar {
                tabBarSnapshot?.removeFromSuperview()
                if let snapShot = tabBarSnapshot {
                    fromVC.view.addSubview(snapShot)
                    snapShot.snp.makeConstraints({ (make) in
                        make.leading.equalToSuperview()
                        make.trailing.equalToSuperview()
                        make.bottom.equalToSuperview()
                        make.height.equalTo(snapShot.bounds.height)
                    })
                    tabBar.alpha = 1
                }
      
            }
            return transition
        }
        return nil
    }`

**Comment by wjwjwj2223** [comment]
I meet it, is there a solution to it?

**Comment by mrfarukturgut** [comment]
@zra95 I am trying to do same thing with modal presentation. Could not find a solution, transition is perfect however Tabbar just hides or show itself immediately after transition is over. Can you explain and maybe share some code?

**Comment by halpz** [comment]
@JoeMatt why close this? needs reopening
