### ISSUE TITLE
Hero Cocoapods Release

### ISSUE THREAD

**Issue by joeljfischer** [HeroTransitions/Hero#633]
## What did you do?

View my outdated pods (which includes Hero) to update to Hero 1.5.0

## What did you expect to happen?

That Hero 1.5.0 would be found

##  What happened instead?

Hero 1.5.0 was not found

## General Information

I believe that while the podspec was updated, the podspec was not released with `pod trunk push NAME.podspec`

**Comment by weixianlove** [comment]
I use this, successfully installed  Hero 1.5.0
```  
pod 'Hero', :git => 'https://github.com/HeroTransitions/Hero.git'
```

**Comment by kuyazee** [comment]
Looks like it wasn't pushed, see [specs](https://github.com/CocoaPods/Specs/tree/b4251aa4ccf0a46aee06c40970eb937ddd3b6383/Specs/e/0/a/Hero), will look into it.

**Comment by kuyazee** [comment]
![Screen Shot 2019-11-08 at 10 31 17 PM](https://user-images.githubusercontent.com/17846698/68484020-81302000-0277-11ea-84fa-029e1679d7c0.png)

Version 1.5.0 has been released, thanks for the heads up guys.
