### ISSUE TITLE
When presenting another ViewController, the transition source disappears.

### ISSUE THREAD

**Issue by hanawat** [HeroTransitions/Hero#641]
Hero is very useful. Thanks.

## What did you do?

The problem I'm encountering occurs when I present another ViewControllerB on ViewControllerA. (Hero is enabled for both ViewControllers)

As soon as ViewControllerB is presented, ViewControllerA disappears with the reversed animation.

```
RootViewController
  └ ViewControllerA (disappear)
      └ ViewControllerB
```

## What did you expect to happen?

I want ViewControllerA to be displayed as it is while ViewControllerB of OverCurrentContext is displayed.

When HeroModifiers is specified, it seems to automatically reverse animation when presenting another ViewController.

Can this be disabled only for present? (I don't want to disable it when appear or dismiss of ViewControllerA itself)

* Hero Version: 1.4.0

* iOS Version(s): 13.2

* Swift Version: 5.1

* Devices/Simulators: iPhone 11 Pro (Simulators)

## Demo Project

The operation is as follows.
https://gfycat.com/meanilliteratebinturong

**Comment by zishanj** [comment]
hero should be enabled only on target viewcontroller only.

**Comment by hanawat** [comment]
@zishanj Thank you for answering!

I found that preventing `heroModifiers` by making them empty or `nil`. It was not possible with `hero.isEnabled = false`. The sample is below.
https://github.com/hanawat/hero-playground/blob/master/HeroPlayground/ViewController.swift

**Comment by hanawat** [comment]
I found one more thing. It was impossible if `isEnabled` was set to `true` for ViewController on Storyboard. Must be specified in code.

<img width="272" alt="スクリーンショット 2019-11-14 22 45 28" src="https://user-images.githubusercontent.com/11912668/68862412-bbdf0000-0730-11ea-80c6-ea64a9204acd.png">
