### ISSUE TITLE
How to increase the duration of the animation while dismissing?

### ISSUE THREAD

**Issue by EfraimB** [HeroTransitions/Hero#643]
## What did you do?

targetView.hero.modifiers = [ .whenDisappearing(.duration(5.0))]

## What did you expect to happen?

The dismiss animation to be the specified duration.

##  What happened instead?

The dismiss animation kept the same animation speed.

* Reproducible in Examples? (Yes/No):

Can be reproducible in any instance.

**Comment by sultan-arshi** [comment]
+1
