### ISSUE TITLE
Pan gesture based dismiss is still buggy

### ISSUE THREAD

**Issue by Kolos65** [HeroTransitions/Hero#655]
## What did you do?
Using Hero's progress update functionality when dismissing a VC on a pan gesture causes many issues. 

- If you use the code in the example project (see below), the first issue is that on a fast pan, the screen freezes because the snapshot stays on the screen. 

- Some people suggested, that explicitly putting `Hero.shared.cancel()` and `Hero.shared.finish()` on the main thread fixes this issue.  This is partly true, but it introduces an other issue: now the screen won't freeze on a fast pan gesture, but the animations are skipped. On fast pans, the modifiers are ignored and the panned view snaps to its place in the parent VC in a strange buggy way.

- The only fix that solves these problems is to put finish and cancel to the main thread, and also detect fast pans and delay the dismissal manually, which is a really ugly, hacky, ad-hoccy solution.

## What did you expect to happen?
Using the code below should be able to handle pan gesture based VC dismissal, even when pan gestures are really fast.

## General Information

* Hero Version: 1.5.0, 1.4.0

* iOS Version(s): 13.3, 12.1

* Swift Version: Swift 5, Swift 4.2

* Devices/Simulators: iPhone 11 Pro, iPhone X

* Reproducible in Examples?: Yes

## Demo Project (Hero Examples / ImageGallery)
```
@objc func pan() {
    let translation = panGR.translation(in: nil)
    let progress = translation.y / 2 / collectionView!.bounds.height
    switch panGR.state {
    case .began:
      hero.dismissViewController()
    case .changed:
      Hero.shared.update(progress)
      if let cell = collectionView?.visibleCells[0]  as? ScrollingImageCell {
        let currentPos = CGPoint(x: translation.x + view.center.x, y: translation.y + view.center.y)
        Hero.shared.apply(modifiers: [.position(currentPos)], to: cell.imageView)
      }
    default:
      if progress + panGR.velocity(in: nil).y / collectionView!.bounds.height > 0.3 {
        Hero.shared.finish()
      } else {
        Hero.shared.cancel()
      }
    }
}
```

PS: In my humble opinion, this is a really common use-case for Hero and I really want it to work seamlessly, but I was unable to figure it out on my own. Send help.

**Comment by francesc-o** [comment]
Hi, is there any news about this bug and related fix?
