### ISSUE TITLE
Swift 5.x

### ISSUE THREAD

**Issue by ergunkocak** [HeroTransitions/Hero#662]
Hello,

First of all thanks for great library. 👍 
Is there a plan for swift 5.x support?
I saw 3 pull requests failed already.

Best

**Comment by Stan1ey83** [comment]
It's working with Swift 5.2

**Comment by ergunkocak** [comment]
Is there a plan to upgrade the library like writing in Swift 5.x?

**Comment by JoeMatt** [comment]
> Is there a plan to upgrade the library like writing in Swift 5.x?

What do you mean by this? It runs five just fine.

**Comment by ergunkocak** [comment]
Hi @JoeMatt ,
xcode suggests to migrate the Hero library to Swift 5. 
So i am guessing Hero library is not written in swift 5 which is what i was trying to ask. 
Also which can be seen in https://github.com/HeroTransitions/Hero/blob/develop/Hero.podspec as Swift "4.2".

**Comment by ergunkocak** [comment]
You may say "who cares? it works" which i am expecting as the next answer :) 
Each time i "pod update" there is this warning in xcode to migrate swift 5 and each time i click i see this warning popup.
Which is really annoying to click and select do not remind me each time :)
Best

**Comment by ergunkocak** [comment]
In case you do not plan to migrate that would be really helpful if you can give a reason not to migrate the codebase to swift 5 👍

**Comment by JoeMatt** [comment]
OK, first of all, nobody said “Who cares?”.

Sorry, but you failed to accurately describe your issue. Pod update having a warning isn’t the same as being vague about supporting Swift 5, which we do.

There is no reason not to, because we do. If it compilers with the latest version of XCode when Swift 5.x is selected, than it’s supported. 

What you’re seeing is a metadata parsing issue in a 3rd party tool. Rather than bitch about it, make a pull request.

**Comment by ergunkocak** [comment]
Hi @JoeMatt ,

First of all, i love this library.

Second, i am sad that you are using words like "bitch about it". It is really offending 👎 

I specifically wrote "Is there a plan to upgrade the library like **writing in Swift 5.x**?" and you responded "It runs five just fine."

An apology will be appreciated.

Third, i did not push anyone to write it asap. I just asked if there is a plan and if not; i asked for the reason so i hoped to learn something new which i do not know.

Best

**Comment by JoeMatt** [comment]
“ Second, i am sad that you are using words like "bitch about it". It is really offending 👎”

Oh, I’m clutching my pearls. Seriously dude, the pedantic piousness isn’t going to work on me, I couldn’t care less what you think of my character.

Stop being passive aggressive and articulate your actual issue, or perhaps learn about Cocoapods and GitHub forks and submit a pull request.

Thanks.

**Comment by ergunkocak** [comment]
Maybe i should not reply in a passive aggressive way to not reading my answer properly.

I am happy to hear there is a plan write this beautiful library in Swift 5.x

For the rest i am leaving you to the hands of Karma.

**Comment by JoeMatt** [comment]
It’s all good bro. 

I never see what has been done; I only see what remains to be done.
