### ISSUE TITLE
how to disable hero transition for navigationcontroller ?

### ISSUE THREAD

**Issue by imnayandave** [HeroTransitions/Hero#666]
## What did you do?

I wanted Transition animation for PUSH and POP for only 2 ViewControllers from many. 
So , I did this on FirstVC(from which PUSH Transition I Wanted)
        self.navigationController!.hero.isEnabled = true

and it worked from that 

But for now every other ViewController , same Hero transition animation is happening which is UNWANTED

I want the default Navigation Transition for other ViewControllers ..
HELP !!
Thanks

**Comment by Mohit-Allay** [comment]
Hey @imnayandave
Did you find any solution or work around ?

**Comment by bvaladao** [comment]
Did you find any solution? I'd like to know as well @imnayandave

**Comment by JoeMatt** [comment]
If every VC shares the same nav controller then this makes sense.

Each VC will have to disable / re-enable hero in the pre and post push/pop methods. Probably in your prepareForTransition method.
