### ISSUE TITLE
FREE YouTube VIDEO TUTORIAL

### ISSUE THREAD

**Issue by rebeloper** [HeroTransitions/Hero#671]
Hi,
Love Hero. So I made a 12 minutes long YouTube tutorial explaining it: https://www.youtube.com/watch?v=M5GYJnQnT_g

Feel free to add it to the README / Documentation / Cheat Sheet with this image [people tap on images more than on boring links :) ]
![UIViewControllerTransitionAnimation](https://user-images.githubusercontent.com/2488011/83051534-d63a5480-a056-11ea-8ddd-fab5dcf238e6.png)
Hope you like it. I'm open to any feedback.

**Comment by phiasco12** [comment]
Misleading...
