### ISSUE TITLE
13.4.1 transition not working 

### ISSUE THREAD

**Issue by CrazyRedcrownedcrane** [HeroTransitions/Hero#672]
## General Information

* Hero Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in Examples? (Yes/No):

**Comment by CrazyRedcrownedcrane** [comment]
it works namaly on <13.4

**Comment by JoeMatt** [comment]
Closing. Should be fine in 1.6.0. No one else reporting issue.

Please reopen if this continues in current release.
