### ISSUE TITLE
Cannot build with `swift build`

### ISSUE THREAD

**Issue by Endore8** [HeroTransitions/Hero#676]
## What did you do?

Added Hero as SPM dependency to a private framework which is a Swift package too.

## What did you expect to happen?

Running `swift build` on my framework errors with 

##  What happened instead?

Throws errors like:
`HeroAnimatorViewContext.swift:23:8: error: no such module 'UIKit' import UIKit`

## General Information

* Hero Version: **1.5.0**

* iOS Version(s): **13.5**

* Swift Version: **5.1**

* Devices/Simulators: **All**

* Reproducible in Examples? (Yes/No):

## Demo Project

Run `swift build` from the root of Hero project.

**Comment by JoeMatt** [comment]
Fixed in 1.6.0
