### ISSUE TITLE
unarchiveObject(with:) and archivedData(withRootObject:) deprecated in iOS 12.0

### ISSUE THREAD

**Issue by Pe-te** [HeroTransitions/Hero#691]
* Hero Version: 1.5.0

Getting these warnings in Xcode 12:

/iOS/Pods/Hero/Sources/Extensions/UIKit+Hero.swift:30:30: 'unarchiveObject(with:)' was deprecated in iOS 12.0: Use +unarchivedObjectOfClass:fromData:error: instead
/iOS/Pods/Hero/Sources/Extensions/UIKit+Hero.swift:30:68: 'archivedData(withRootObject:)' was deprecated in iOS 12.0: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead

**Comment by sebastien-tribu** [comment]
Same, any risks of this pod breaking if iOS 15 removes this method?

**Comment by JoeMatt** [comment]
Created PR #702
