### ISSUE TITLE
"Example Gallery Blog Post" is dead ⚰💀

### ISSUE THREAD

**Issue by specialfor** [HeroTransitions/Hero#692]
## What did you do?

Read `README.md` and tried to open "Example Gallery Blog Post".

## What did you expect to happen?

"Example Gallery Blog Post" should be valid page.

##  What happened instead?

"The page is not found" error appeared.

## General Information

N/A

## Demo Project

N/A

**Comment by AugustDev** [comment]
I second, please provide examples. Another link in documentation is dead

http://lkzhao.com/2017/02/05/hero-interactive-transition.html

**Comment by JoeMatt** [comment]
Fixed in f737a0a75d9a721b21b62a25adf05cf05c5fa3b2 released in 1.6.0
