### ISSUE TITLE
SPM integration causes compiler Issues, preventing the project from building

### ISSUE THREAD

**Issue by joshwoods** [HeroTransitions/Hero#704]
## What did you do?
Installed Hero via SPM and then was not able to actually build the project. See screenshot below.

## What did you expect to happen?
The project should be able to build, however, there are multiple issues throughout the project when integrating via SPM.

##  What happened instead?
![Screen Shot 2021-02-20 at 4 23 36 PM](https://user-images.githubusercontent.com/4240678/108611105-6c0dd080-7398-11eb-99dc-e94a8c09c971.png)

## General Information

* Hero Version:
1.6.0

* iOS Version(s):
iOS 14.4

* Devices/Simulators:
iPhone 12 Pro Max

* Reproducible in Examples? (Yes/No):
Yes

## Demo Project
[test.zip](https://github.com/HeroTransitions/Hero/files/6016859/test.zip)

**Comment by JoeMatt** [comment]
SPM is strange with imports. Probably need to add missing `import Foundation`, `import CoreGraphics`.

I had added a bunch and it was building with SPM before my merge. I'll check out your sample project, thanks.

**Comment by JoeMatt** [comment]
@joshwoods Can you point your SPM config to branch `feature/704_SPM_Fixes` and see if it's fixed please.

**Comment by z3bi** [comment]
I was having the same issue but was able to build with SPM using `feature/704_SPM_Fixes`
