### ISSUE TITLE
Black screen on dismiss controller

### ISSUE THREAD

**Issue by GeorgeKyrylenko1998** [HeroTransitions/Hero#705]
## What did you do?

I try to use Hero for present view controller

## What did you expect to happen?
Correct work

##  What happened instead?
Black screen after dismiss controller 

## General Information

* Hero Version: 1.6.0

* iOS Version(s): 14.3

* Swift Version: 5

* Devices/Simulators: Simulators

**Comment by joaomvfsantos** [comment]
I'm experiencing this behaviour too. It does not seem like a crash, at least I get no crashes on Xcode and no error messages whatsoever. As soon as the View Controller finishes dismissing, I get this black screen. Only experiencing this on v.1.6.0

**Comment by davydovct** [comment]
Confirm. Have to go back on 1.5.0

**Comment by elilien** [comment]
Me too. Have to go back on 1.5.0

**Comment by Ru5C55an** [comment]
Me too. Have to go back on 1.5.0

**Comment by meyumeapps** [comment]
Confirmed. Back to 1.5.0.

**Comment by KONGFANJI** [comment]
Me too. Have to go back on 1.5.0

**Comment by JoeMatt** [comment]
I think it's commit 800b9d90238e385df8bb69f5e94887e2d0e7a695

Working on a patch and release for later today.

**Comment by joaomvfsantos** [comment]
I can confirm that it's fixed on 1.6.1. Thank you very much @JoeMatt!
