### ISSUE TITLE
Swift compiler error - Xcode 13 beta 3

### ISSUE THREAD

**Issue by johnnysay** [HeroTransitions/Hero#720]
## What did you do?

I tried to compile a project using Hero.

## What did you expect to happen?

I expected the project to compile.

##  What happened instead?

I got the following compiler error in code using `UIApplication.shared`:
`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

For example in HeroTransition+Complete.swift line 90 :
`
        UIApplication.shared.keyWindow?.addSubview(isPresenting ? fromView : toView)
`
## General Information

* Hero Version: 1.5.0, probably the latest one as well
* iOS Version(s): 15.0
* Swift Version: 5
* Devices/Simulators: iPhone 12 mini

* Reproducible in Examples? (Yes/No): No, I could not reproduce it on a brand new project.

**Comment by JoeMatt** [comment]
hm, I thought this has been fixed in a prior PR.

I'll look into it again. Thanks

**Comment by JoeMatt** [comment]
@johnnysay 1.6.0 should have fixed this actually.
https://github.com/HeroTransitions/Hero/pull/681

We're on 1.6.1 now. I'm going to close, re-open if you update to 1.6.x and still have issues.
