### ISSUE TITLE
I have collectionView and in didselect I am enabling the hero ID to cell but next time its is automatically getting another adjacent cell's content

### ISSUE THREAD

**Issue by sagarmahindrakarshipr** [HeroTransitions/Hero#731]
## General Information

* Hero Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in Examples? (Yes/No):

**Comment by JoeMatt** [comment]
If this is still happening, update with more precise instructions to reproduce.
