### ISSUE TITLE
Crash -- HeroViewPropertyViewContext.swift line 56

### ISSUE THREAD

**Issue by patthehuman** [HeroTransitions/Hero#735]
partial apply for closure #2 in HeroViewPropertyViewContext.resume(timePassed:reverse:)

`Crashed: com.apple.main-thread
0  Hero                           0x58598 partial apply for closure #2 in HeroViewPropertyViewContext.resume(timePassed:reverse:) + 56 (HeroViewPropertyViewContext.swift:56)
1  Hero                           0x3b4a8 thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:28)
2  libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
4  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
5  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
6  CoreFoundation                 0x522f0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
7  CoreFoundation                 0xc1f4 __CFRunLoopRun + 2532
8  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
9  GraphicsServices               0x1374 GSEventRunModal + 164
10 UIKitCore                      0x513e88 -[UIApplication _run] + 1100
11 UIKitCore                      0x2955ec UIApplicationMain + 364
12 Mood App                       0x5294 main + 25 (AppDelegate.swift:25)
13 ???                            0x1038e9ce4 (Missing)`

Appears line 52 needs some optional question marks.

**Comment by JoeMatt** [comment]
Maybe this is a divide by zero,
```swift
      viewPropertyAnimator.fractionComplete = CGFloat(1.0 - timePassed / duration)
```

I'll update this function in a PR you can test.

**Comment by JoeMatt** [comment]
Created #736
