### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by liwei5544** [HeroTransitions/Hero#738]
## General Information

* Hero Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in Examples? (Yes/No):

## Demo Project

fatal error: Unexpected Swift version: file /Users/marcelofabri/Westfield/SwiftLint/Source/SwiftLintFramework/Models/SwiftVersion.swift, line 38
/Users/hxtj/Library/Developer/Xcode/DerivedData/Hero-eialgouwhjevvfdnlygwqcbbrjxl/Build/Intermediates.noindex/Hero.build/Debug-iphonesimulator/HeroExamples.build/Script-A0BDF7221E2FCC5A0028778F.sh: line 6: 15619 Illegal instruction: 4  swiftlint
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by JoeMatt** [comment]
looks like a swift/xcode issue.

Clear derived data and refresh packages and try again.
Re-open if it's still not working.
