### ISSUE TITLE
Doesn't the demo project work?

### ISSUE THREAD

**Issue by alexanderkhitev** [HeroTransitions/Hero#761]
Hello! Doesn't the demo project work? Thanks.

**Comment by cruisediary** [comment]
Hello @alexanderkhitev  The demo of Hero Transition is running smoothly. Please ensure that you have the latest version of Xcode installed and double-check that your Xcode scheme is set to "HeroExamples" for building.

<img width="1000" alt="Demo" src="https://github.com/HeroTransitions/Hero/assets/2609775/5c7f8420-6b62-4488-8b25-10f382e8b831">

**Comment by alexanderkhitev** [comment]
> Hello @alexanderkhitev The demo of Hero Transition is running smoothly. Please ensure that you have the latest version of Xcode installed and double-check that your Xcode scheme is set to "HeroExamples" for building.
> 
> <img alt="Demo" width="1000" src="https://user-images.githubusercontent.com/2609775/251963850-5c7f8420-6b62-4488-8b25-10f382e8b831.png">

Hey @cruisediary ! Ok, thank you!
