### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by niji-mathieu-viel** [HeroTransitions/Hero#774]
Hi guys.

I think that the library may be impacted by this new rule by Apple; from what I understand, as the library is not collecting any personal data, an empty manifest + podspec / package.swift setup should do the trick (?) 

Third-party SDKs should include a privacy manifest by Spring according to Apple new requirements :
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc

Thanks.

**Comment by aiKrice** [comment]
The library is not impacted according the documentation. This ticket could be closed @JoeMatt
