### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by yangdehui** [HeroTransitions/Hero#775]
The real machine reports an error when running, but the simulator runs normally.
Install via cocoapods
pod 'Hero', '~> 1.6' # https://github.com/lkzhao/Hero

dyld[10115]: Library not loaded: @rpath/Hero.framework/Hero
   Referenced from: <C8648121-5C0F-356D-AD05-547881724848> /private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/SSR20240129
   Reason: tried: '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero ' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero. framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/ Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno= 2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A- DD73-4F35-B613-05EFB666A7ED/SSR20240129.App/Frameworks/Hero.framework/Hero '(Errno = 2),'/Prive/VAR/Bundle/Application/981653 0A-DD73-4F35-B613-05EFB666A7ED/SSR20240129. app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/preboot/Cryptexes/OS@rpath/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno= 2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A- DD73-4F35-B613-05EFB666A7ED/SSR20240129.App/Frameworks/Hero.framework/Hero '(Errno = 2),'/Prive/VAR/Bundle/Application/981653 0A-DD73-4F35-B613-05EFB666A7ED/SSR20240129. app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework /Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/ Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2 ), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/ Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/System/Library/Frameworks/Hero.framework/Hero' (errno=2 , not in dyld cache)
Library not loaded: @rpath/Hero.framework/Hero
   Referenced from: <C8648121-5C0F-356D-AD05-547881724848> /private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/SSR20240129
   Reason: tried: '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero.framework/Hero ' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Hero. framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/private/var/containers/Bundle/ Application/9816530A-DD73-4F35-B613-05EFB666A7ED/SSR20240129.app/Frameworks/Hero.framework/Hero' (errno=2), '/usr/lib/swift/Hero.framework/Hero' (errno=2, not in dyld cache), '/private/preboot/
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport .framework/libViewDebuggerSupport.dylib

**Comment by JoeMatt** [comment]
This doesn't appear to be an issue with the library but rather a user environment issue
